# Generated by Django 4.2.21 on 2025-07-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.TextField()),
                ('original_pvc_path', models.TextField(blank=True, null=True)),
                ('watermarked_pvc_path', models.TextField(blank=True, null=True)),
                ('original_s3_path', models.TextField(blank=True, null=True)),
                ('watermarked_s3_path', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'image_index',
            },
        ),
    ]
