# Generated by Django 5.2.14 on 2026-08-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0002_imageindex_created_at_imageindex_modified_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='imageindex',
            index=models.Index(fields=['camera_id', '-timestamp'], name='image_index_camera__6083f3_idx'),
        ),
    ]
