apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.fullname" . }}
  labels: {{ include "app.labels" . | nindent 4 }}
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: nginx
  internalTrafficPolicy: Cluster
  selector:
    {{ include "app.selectorLabels" . | nindent 4 }}