kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ template "app.fullname" . }}
  labels: {{ include "app.labels" . | nindent 4 }}
{{ if .Values.route.iprestricted }}
  annotations:
    haproxy.router.openshift.io/ip_whitelist: {{ .Values.route.ipallowlist  }}
{{ end }}
spec:
  host: {{ .Values.route.host }}
  to:
    kind: Service
    name: {{ template "app.fullname" . }}
    weight: 100
  port:
    targetPort: oauth-proxy
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

