apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "app.fullname" . }}
  namespace: a781ec-dev
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"{{ template "app.fullname" . }}"}}'
  labels: {{ include "app.labels" . | nindent 4 }}