apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.fullname" . }}
  labels: {{ include "app.labels" . | nindent 4 }}
spec:
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: 6379-tcp
  internalTrafficPolicy: Cluster
  selector:
    {{ include "app.selectorLabels" . | nindent 4 }}