FROM alpine:3.20
RUN apk update && apk upgrade

RUN apk add --no-cache \
    aws-cli \
    bash \
    coreutils \
    goaccess \
    ca-certificates \
    tzdata

#Two lines below can be removed after July 2025. Workaround for Entrust Root Cert distrust. Object Storage will get new cert in July. See DBC22-3249   
COPY ./compose/openshiftjobs/root.crt /usr/local/share/ca-certificates/
RUN update-ca-certificates

COPY ./compose/openshiftjobs/entrypoint.sh /
COPY ./compose/openshiftjobs/scripts/analyzeexportlogs.sh /scripts/
COPY ./compose/openshiftjobs/scripts/backupmediapvc.sh /scripts/
COPY ./compose/openshiftjobs/scripts/ziplogs.sh /scripts/

RUN sed -i 's/\r$//g' /entrypoint.sh && chmod +x /entrypoint.sh
RUN sed -i 's/\r$//g' /scripts/analyzeexportlogs.sh && chmod +x /scripts/analyzeexportlogs.sh
RUN sed -i 's/\r$//g' /scripts/backupmediapvc.sh && chmod +x /scripts/backupmediapvc.sh
RUN sed -i 's/\r$//g' /scripts/ziplogs.sh && chmod +x /scripts/ziplogs.sh


ENTRYPOINT ["/entrypoint.sh"]