apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.fullname" . }}
  labels: {{ include "app.labels" . | nindent 4 }}
spec:
  ports:
    - name: 80-tcp
      port: 80
      targetPort: 8000
      protocol: TCP
  internalTrafficPolicy: Cluster
  selector:
    {{ include "app.selectorLabels" . | nindent 4 }}