kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "app.fullname" . }}
  labels: {{ include "app.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.mediapvc.storage }}

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "app.fullname" . }}-app-images
  labels: {{ include "app.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.apppvc.storage }}