# Generated by Django 4.2.1 on 2023-07-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcam', '0002_alter_webcam_highway_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webcam',
            name='orientation',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='webcam',
            name='region',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='webcam',
            name='highway_description',
            field=models.CharField(blank=True, default='', max_length=128),
            preserve_default=False,
        ),
    ]
