# Generated by Django 4.2.1 on 2023-07-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcam', '0003_alter_webcam_orientation_alter_webcam_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webcam',
            name='orientation',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
