# Generated by Django 4.2.1 on 2023-10-06 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcam', '0005_alter_webcam_update_period_mean_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webcam',
            name='caption',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
