# Generated by Django 4.2.3 on 2024-03-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcam', '0006_alter_webcam_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcam',
            name='credit',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='webcam',
            name='dbc_mark',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
