# Generated by Django 4.2.3 on 2024-04-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcam', '0007_webcam_credit_webcam_dbc_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcam',
            name='route_order',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
