# Generated by Django 4.2.16 on 2025-07-02 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_area'),
        ('webcam', '0008_webcam_route_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcam',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.area'),
        ),
    ]
