# Generated by Django 4.2.22 on 2025-08-29 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0016_currentweather_code'),
        ('webcam', '0010_webcam_group_webcam_nearby_objs'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcam',
            name='hev_station',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='weather.highelevationforecast'
            ),
        ),
        migrations.AddField(
            model_name='webcam',
            name='local_weather_station',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='weather.currentweather'
            ),
        ),
        migrations.AddField(
            model_name='webcam',
            name='regional_weather_station',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='weather.regionalweather'
            ),
        )
    ]
