# Generated by Django 4.2.21 on 2025-07-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcam', '0010_webcam_group_webcam_nearby_objs'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcam',
            name='https_cam',
            field=models.BooleanField(default=False),
        ),
    ]
