# Generated by Django 4.2.16 on 2025-07-16 00:56

import django.db.models.deletion
from apps.webcam.tasks import update_all_camera_group_ids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcam', '0010_webcam_https_cam'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcam',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webcam.webcam'),
        ),
        migrations.AddField(
            model_name='webcam',
            name='nearby_objs',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(update_all_camera_group_ids),
    ]
