# Generated by Django 4.2.22 on 2025-08-29 20:35

import django.db.models.deletion
from apps.webcam.tasks import update_camera_relations
from django.db import migrations, models


def update_relations(apps, schema_editor):
    update_camera_relations()


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0016_currentweather_code'),
        ('webcam', '0011_webcam_https_cam'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcam',
            name='hev_station',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='weather.highelevationforecast'
            ),
        ),
        migrations.AddField(
            model_name='webcam',
            name='local_weather_station',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='weather.currentweather'
            ),
        ),
        migrations.AddField(
            model_name='webcam',
            name='regional_weather_station',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='weather.regionalweather'
            ),
        ),
        migrations.RunPython(update_relations),
    ]
