# Generated by Django 4.2.22 on 2025-12-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcam', '0012_webcam_https_cam'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraSource',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cam_internetname', models.CharField(blank=True, max_length=255, null=True)),
                ('cam_internetcaption', models.CharField(blank=True, max_length=255, null=True)),
                ('cam_internetcredit', models.CharField(blank=True, max_length=255, null=True)),
                ('cam_internetcomments', models.TextField(blank=True, null=True)),
                ('cam_internetwebsite_url', models.CharField(blank=True, max_length=500, null=True)),
                ('cam_internetgetfile2_url', models.CharField(blank=True, max_length=500, null=True)),
                ('cam_internetdrivebc_url', models.CharField(blank=True, max_length=500, null=True)),
                ('cam_internetftp_path', models.CharField(blank=True, max_length=500, null=True)),
                ('cam_internetftp_folder', models.CharField(blank=True, max_length=255, null=True)),
                ('cam_internetftp_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('cam_internetdisplay_folder', models.CharField(blank=True, max_length=255, null=True)),
                ('cam_internetdisplay_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('cam_internetcontact_notes', models.TextField(blank=True, null=True)),
                ('cam_internetdbc_mark', models.CharField(blank=True, max_length=255, null=True)),
                ('cam_internetinset_horizontal', models.CharField(blank=True, max_length=255, null=True)),
                ('cam_internetupdated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('cam_internetlast_updated', models.DateTimeField(blank=True, null=True)),
                ('cam_locationsregion', models.CharField(blank=True, max_length=255, null=True)),
                ('cam_locationsbusiness_area', models.CharField(blank=True, max_length=255, null=True)),
                ('cam_locationshighway', models.CharField(blank=True, max_length=255, null=True)),
                ('cam_locationshighway_section', models.CharField(blank=True, max_length=255, null=True)),
                ('cam_locationsorientation', models.CharField(blank=True, max_length=50, null=True)),
                ('cam_locationslandmark', models.CharField(blank=True, max_length=255, null=True)),
                ('cam_locationscrossroad', models.CharField(blank=True, max_length=255, null=True)),
                ('cam_locationselevation', models.IntegerField(blank=True, null=True)),
                ('cam_locationscam_group', models.CharField(blank=True, max_length=255, null=True)),
                ('cam_locationsgeo_latitude', models.CharField(blank=True, max_length=255, null=True)),
                ('cam_locationsgeo_longitude', models.CharField(blank=True, max_length=255, null=True)),
                ('cam_locationsalbers_northing', models.CharField(blank=True, max_length=255, null=True)),
                ('cam_locationsalbers_easting', models.CharField(blank=True, max_length=255, null=True)),
                ('cam_locationssegment', models.CharField(blank=True, max_length=255, null=True)),
                ('cam_locationslrs_node', models.CharField(blank=True, max_length=255, null=True)),
                ('cam_locationsdd', models.CharField(blank=True, max_length=255, null=True)),
                ('cam_locationsmap_art_no', models.CharField(blank=True, max_length=255, null=True)),
                ('cam_locationsthumbnail_map_url', models.CharField(blank=True, max_length=500, null=True)),
                ('cam_locationsregional_map_url', models.CharField(blank=True, max_length=500, null=True)),
                ('cam_locationsupdated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('cam_locationslast_updated', models.DateTimeField(blank=True, null=True)),
                ('cam_controldisabled', models.BooleanField(default=False)),
                ('isnew', models.BooleanField(default=False)),
                ('cam_maintenanceis_on_demand', models.BooleanField(default=False)),
                ('seq', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Cams_Live',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Highway',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hwy_number', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Highways_Live',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('seq', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Regions_Live',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegionHighway',
            fields=[
                ('highway_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('region_id', models.CharField(max_length=20)),
                ('seq', models.IntegerField()),
            ],
            options={
                'db_table': 'Region_Highways_Live',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='webcam',
            name='caption_override',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='webcam',
            name='name_override',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
