# Generated by Django 5.2.12 on 2026-05-06 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcam', '0013_camerasource_highway_region_regionhighway_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webcam',
            name='is_on',
        ),
    ]
