# Generated by Django 5.2.14 on 2026-06-10 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webcam", "0013_camerasource_highway_region_regionhighway_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="webcam",
            name="update_weather_stations",
            field=models.BooleanField(default=True),
        ),
    ]
