# Generated by Django 5.2.16 on 2026-09-19 01:48

import sys

from django.db import migrations


def rebuild_camera_order(apps, schema_editor):
    if "test" in sys.argv:
        return

    from apps.webcam.tasks import add_order_to_cameras, build_route_geometries

    build_route_geometries()
    add_order_to_cameras()


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("webcam", "0014_webcam_update_weather_stations"),
    ]

    operations = [
        migrations.RunPython(rebuild_camera_order, noop_reverse),
    ]
