# Generated by Django 5.2.12 on 2026-05-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcam', '0014_remove_webcam_is_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcam',
            name='is_on',
            field=models.BooleanField(default=True),
        ),
    ]
