# Generated by Django 4.2.11 on 2024-07-05 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webcam', '0008_webcam_route_order'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouritedCameras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webcams', to=settings.AUTH_USER_MODEL)),
                ('webcam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='webcam.webcam')),
            ],
        ),
        migrations.AddConstraint(
            model_name='favouritedcameras',
            constraint=models.UniqueConstraint(fields=('user', 'webcam'), name='user_webcam'),
        ),
    ]
