# Generated by Django 4.2.11 on 2024-07-08 16:12

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_favouritedcameras_favouritedcameras_user_webcam'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedRoutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('route', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
                ('start', models.TextField(blank=True)),
                ('start_point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('end', models.TextField(blank=True)),
                ('end_point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('validated', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
