# Generated by Django 4.2.11 on 2024-07-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_savedroutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedroutes',
            name='distance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='savedroutes',
            name='distance_unit',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='savedroutes',
            name='label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='savedroutes',
            name='thumbnail',
            field=models.TextField(null=True),
        ),
    ]
