# Generated by Django 4.2.3 on 2024-10-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0004_savedroutes_distance_savedroutes_distance_unit_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedroutes",
            name="distance",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="savedroutes",
            name="thumbnail",
            field=models.TextField(blank=True, null=True),
        ),
    ]
