# Generated by Django 4.2.16 on 2024-11-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_savedroutes_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedroutes',
            name='criteria',
            field=models.CharField(default='fastest', max_length=100),
        ),
    ]
