# Generated by Django 4.2.16 on 2024-11-01 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_savedroutes_criteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedroutes',
            name='searchTimestamp',
            field=models.CharField(default='fastest', max_length=100),
        ),
    ]
