# Generated by Django 4.2.16 on 2024-12-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_drivebcuser_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedroutes',
            name='notification',
            field=models.BooleanField(default=False),
        ),
    ]
