# Generated by Django 4.2.16 on 2025-01-14 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_savedroutes_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivebcuser',
            name='attempted_verification',
            field=models.BooleanField(default=False),
        ),
    ]
