# Generated by Django 4.2.16 on 2025-01-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_drivebcuser_attempted_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedroutes',
            name='notification_days',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='savedroutes',
            name='notification_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedroutes',
            name='notification_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedroutes',
            name='notification_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedroutes',
            name='notification_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedroutes',
            name='notification_types',
            field=models.JSONField(default=list),
        ),
        migrations.AddIndex(
            model_name='savedroutes',
            index=models.Index(fields=['user', 'notification'], name='authenticat_user_id_b59a01_idx'),
        ),
        migrations.AddIndex(
            model_name='savedroutes',
            index=models.Index(fields=['notification_days'], name='authenticat_notific_fae920_idx'),
        ),
        migrations.AddIndex(
            model_name='savedroutes',
            index=models.Index(fields=['notification_start_date'], name='authenticat_notific_86cbaf_idx'),
        ),
        migrations.AddIndex(
            model_name='savedroutes',
            index=models.Index(fields=['notification_end_date'], name='authenticat_notific_e67ca2_idx'),
        ),
        migrations.AddIndex(
            model_name='savedroutes',
            index=models.Index(fields=['notification_start_time'], name='authenticat_notific_e93d11_idx'),
        ),
        migrations.AddIndex(
            model_name='savedroutes',
            index=models.Index(fields=['notification_end_time'], name='authenticat_notific_1b368a_idx'),
        ),
    ]
