# Generated by Django 4.2.22 on 2025-10-10 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_savedroutes_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivebcuser',
            name='attempted_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drivebcuser',
            name='consent',
            field=models.BooleanField(default=False),
        ),
    ]
