# Generated by Django 5.2.14 on 2026-07-10 22:32

import django.db.models.deletion
import django_prometheus.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0014_drivebcuser_attempted_consent_drivebcuser_consent"),
        ("shared", "0004_populate_areas"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("notification", models.BooleanField(blank=True, default=False)),
                ("notification_types", models.JSONField(blank=True, default=list)),
                ("notification_days", models.JSONField(blank=True, default=list)),
                ("notification_start_date", models.DateField(blank=True, null=True)),
                ("notification_end_date", models.DateField(blank=True, null=True)),
                ("notification_start_time", models.TimeField(blank=True, null=True)),
                ("notification_end_time", models.TimeField(blank=True, null=True)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_subscriptions",
                        to="shared.area",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "notification"],
                        name="authenticat_user_id_6ab31b_idx",
                    ),
                    models.Index(
                        fields=["notification_days"],
                        name="authenticat_notific_62f553_idx",
                    ),
                    models.Index(
                        fields=["notification_start_date"],
                        name="authenticat_notific_bca46b_idx",
                    ),
                    models.Index(
                        fields=["notification_end_date"],
                        name="authenticat_notific_aaf2f2_idx",
                    ),
                    models.Index(
                        fields=["notification_start_time"],
                        name="authenticat_notific_bf7cbf_idx",
                    ),
                    models.Index(
                        fields=["notification_end_time"],
                        name="authenticat_notific_7d7193_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("user", "area"), name="user_area")
                ],
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin(
                    "email-subscriptions"
                ),
                models.Model,
            ),
        ),
    ]
