# Generated by Django 4.2.16 on 2024-11-23 01:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ferry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('route_id', models.PositiveSmallIntegerField()),
                ('route_name', models.CharField(blank=True, default='', max_length=128)),
                ('route_description', models.CharField(blank=True, default='', max_length=750)),
                ('url', models.URLField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('route_image_url', models.URLField(blank=True)),
                ('location', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('vehicle_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('passenger_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('crossing_time_min', models.PositiveIntegerField(blank=True, null=True)),
                ('weight_capacity_kg', models.PositiveIntegerField(blank=True, null=True)),
                ('schedule_type', models.CharField(blank=True, default='', max_length=64)),
                ('schedule_detail', models.CharField(blank=True, default='', max_length=750)),
                ('special_restriction', models.CharField(blank=True, default='', max_length=750)),
                ('contact_org', models.CharField(blank=True, default='', max_length=128)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=32)),
                ('contact_alt_phone', models.CharField(blank=True, default='', max_length=32)),
                ('contact_fax', models.CharField(blank=True, default='', max_length=32)),
                ('webcam_url_1', models.URLField(blank=True)),
                ('webcam_url_2', models.URLField(blank=True)),
                ('webcam_url_3', models.URLField(blank=True)),
                ('webcam_url_4', models.URLField(blank=True)),
                ('webcam_url_5', models.URLField(blank=True)),
                ('feed_created_at', models.DateTimeField(auto_now_add=True)),
                ('feed_modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
