# Generated by Django 4.2.16 on 2024-11-25 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferry',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='ferry',
            name='contact_url_1',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='ferry',
            name='contact_url_2',
            field=models.URLField(blank=True),
        ),
    ]
