# Generated by Django 4.2.16 on 2025-01-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferry', '0002_ferry_contact_email_ferry_contact_url_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ferry',
            name='schedule_detail',
            field=models.TextField(blank=True, default=''),
        ),
    ]
