# Generated by Django 4.2.16 on 2025-06-20 22:22

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferry', '0003_alter_ferry_schedule_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoastalFerryCalendar',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('schedule_start', models.DateField()),
                ('schedule_end', models.DateField()),
                ('active_week_days', models.CharField(
                    blank=True,
                    help_text='Comma-separated weekdays (e.g. monday,tuesday,wednesday)',
                    max_length=128
                )),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CoastalFerryRoute',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CoastalFerryStop',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('location', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('parent_stop', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='child_stops',
                    to='ferry.coastalferrystop'
                )),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CoastalFerryTrip',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('calendar', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='trips',
                    to='ferry.coastalferrycalendar'
                )),
                ('route', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='trips',
                    to='ferry.coastalferryroute'
                )),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CoastalFerryStopTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('stop_time', models.CharField()),
                ('stop_sequence', models.PositiveSmallIntegerField()),
                ('stop', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, related_name='stop_times',
                    to='ferry.coastalferrystop'
                )),
                ('trip', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, related_name='stop_times',
                    to='ferry.coastalferrytrip'
                )),
            ],
            options={
                'unique_together': {('trip', 'stop')},
            },
        ),
    ]
