# Generated by Django 4.2.22 on 2025-11-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferry', '0004_coastalferrycalendar_coastalferryroute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferry',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
