# We are creating a Role for the Service Account to be able to read the PostgresCluster CRD
# To avoid issues with upgrades, we only create the Role if the release is an initial install
# and keep the resource if the release is deleted so that the Role is not deleted when an 
# admin tries to do an upgrade
{{- if and .Values.serviceaccount.enabled (not .Release.IsUpgrade) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
rules:
- apiGroups:
  - postgres-operator.crunchydata.com
  resources:
  - postgresclusters
  verbs:
  - get
  - list
  - read
{{- end }}
