# We are creating a RoleBinding for the Service Account to be able to read the PostgresCluster CRD
# To avoid issues with upgrades, we only create the RoleBinding if the release is an initial install
# and keep the resource if the release is deleted so that the RoleBinding is not deleted when an 
# admin tries to do an upgrade
{{- if and .Values.serviceaccount.enabled (not .Release.IsUpgrade) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "app.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "app.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}