# We are creating a Secret for the Service Account to be able to read the PostgresCluster CRD
# To avoid issues with upgrades, we only create the Secret if the release is an initial install
# and keep the resource if the release is deleted so that the Secret is not deleted when an 
# admin tries to do an upgrade
{{- if and .Values.serviceaccount.enabled (not .Release.IsUpgrade) }}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: {{ template "app.fullname" . }}
    "helm.sh/resource-policy": keep
  name: {{ template "app.fullname" . }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/service-account-token
{{- end }}
