apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "crunchy-postgres.fullname" . }}-allow-same-namespace
spec:
  podSelector:
    matchLabels:
      postgres-operator.crunchydata.com/cluster: {{ include "crunchy-postgres.fullname" . }}
  ingress:
    - from:
        {{- range .Values.networkPolicy.ingressFromSelectors }}
        - podSelector:
            matchLabels:
              {{- toYaml . | nindent 14 }}
        {{- end }}
  policyTypes:
    - Ingress