apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "crunchy-postgres.fullname" . }}-allow-same-namespace
spec:
  podSelector: {}
  ingress:
    - from:
        - podSelector: {}
  policyTypes:
    - Ingress