{{- if and .Values.pgBackRest.s3.enabled .Values.pgBackRest.s3.createS3Secret }}
{{- if not (lookup "v1" "Secret" .Release.Namespace .Values.pgBackRest.s3.s3Secret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pgBackRest.s3.s3Secret }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  {{- $args := dict "s3" .Values.pgBackRest.s3 "index" 1 }}
  s3.conf: |-
        {{ include "postgres.s3" $args | b64enc }}
{{- end }}
{{- end }}