{{- if and .Values.crunchy.enabled .Values.crunchy.pgBackRest.s3.enabled }}
{{- if not (lookup "v1" "Secret" .Release.Namespace (printf "%s-s3-secret" .Release.Name)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-s3-secret
  labels: {{ include "crunchy-postgres.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
stringData:
  s3.conf: |-
    {{ include "crunchy.s3" . | nindent 8 }}
{{- end }}
{{- end }}