# Generated by Django 4.2.1 on 2023-06-01 00:25

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('start_point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('destination_point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('route_points', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('criteria', models.CharField(choices=[('fastest', 'Fastest'), ('shortest', 'Shortest')], default='fastest', max_length=10)),
                ('srs_code', models.CharField(max_length=5)),
                ('distance_unit', models.CharField(choices=[('km', 'km'), ('mi', 'mi')], default='km', max_length=2)),
                ('distance', models.FloatField(help_text='Length of route in distance units')),
                ('route_time', models.FloatField(help_text='Duration in seconds')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TravelAdvisoryMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='Publication date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Travel Advisory Message',
            },
        ),
    ]
