kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "app.fullname" . }}-log-storage
  labels: {{ include "app.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.logpvc.storage }}