apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.fullname" . }}-frontend
  labels: {{ include "app.labels" . | nindent 4 }}
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  internalTrafficPolicy: Cluster
  selector:
    {{ include "app.selectorLabels" . | nindent 4 }}