#!/bin/sh

# Check if maintenance mode is enabled
if [ "$MAINTENANCE_MODE" = "true" ]; then
    echo "Maintenance mode is enabled. Updating Nginx configuration and skipping the rest of the script..."
    cp /etc/nginx/default_maintenance.txt /etc/nginx/conf.d/default.conf
    # Exit script
    exit 0
fi

# Find main files
MAIN=`find /usr/share/nginx/html/static/js/main.*.js`
MAINCSS=`find /usr/share/nginx/html/static/css/main.*.css`
MAINSVG=`find /usr/share/nginx/html/static/media/*.svg`

# Append environment variables to main JS file
echo -e "\nwindow.BASE_MAP='${REACT_APP_BASE_MAP}';" >> $MAIN
echo -e "window.MAP_STYLE='${REACT_APP_MAP_STYLE}';" >> $MAIN
echo -e "window.API_HOST='${REACT_APP_API_HOST}';" >> $MAIN
echo -e "window.REPORT_WMS_LAYER='${REACT_APP_REPORT_WMS_LAYER}';" >> $MAIN
echo -e "window.GEOCODER_HOST='${REACT_APP_GEOCODER_HOST}';" >> $MAIN
echo -e "window.GEOCODER_API_CLIENT_ID='${REACT_APP_GEOCODER_API_CLIENT_ID}';" >> $MAIN
echo -e "window.ROUTE_PLANNER='${REACT_APP_ROUTE_PLANNER}';" >> $MAIN
echo -e "window.ROUTE_PLANNER_CLIENT_ID='${REACT_APP_ROUTE_PLANNER_CLIENT_ID}';" >> $MAIN
echo -e "window.REPLAY_THE_DAY='${REACT_APP_REPLAY_THE_DAY}';" >> $MAIN
echo -e "window.SURVEY_LINK='${REACT_APP_SURVEY_LINK}';" >> $MAIN
echo -e "window.BCEID_REGISTER_URL='${REACT_APP_BCEID_REGISTER_URL}';" >> $MAIN
echo -e "window.FROM_EMAIL='${REACT_APP_FROM_EMAIL}';" >> $MAIN
echo -e "window.LEGACY_URL='${REACT_APP_LEGACY_URL}';" >> $MAIN
echo -e "window.RECAPTCHA_CLIENT_ID='${REACT_APP_RECAPTCHA_CLIENT_ID}';" >> $MAIN
echo -e "window.ALTERNATE_ROUTE_GDF='${REACT_APP_ALTERNATE_ROUTE_GDF}';" >> $MAIN
echo -e "window.ALTERNATE_ROUTE_TURNCOST='${REACT_APP_ALTERNATE_ROUTE_TURNCOST}';" >> $MAIN
echo -e "window.ALTERNATE_ROUTE_XINGCOST='${REACT_APP_ALTERNATE_ROUTE_XINGCOST}';" >> $MAIN
echo -e "window.DEPLOYMENT_TAG='${DEPLOYMENT_TAG}';" >> $MAIN
echo -e "window.RELEASE='${RELEASE:-}';" >> $MAIN

# Set the environment to be used for caching django content
sed -i "s~{ENVIRONMENT}~$ENVIRONMENT~g" /etc/nginx/conf.d/default.conf

# Check if the environment is 'prod' so that we remove the noindex header
if [ "$ENVIRONMENT" = "prod-drivebc" ]; then
    echo "Environment is 'prod' removing X-Robots-Tag noindex header."
    sed -i '/add_header X-Robots-Tag "noindex";/d' /etc/nginx/conf.d/security_headers.conf
else
    echo "Environment is not 'prod', keeping X-Robots-Tag noindex header."
fi

#precompress the main js and css files to improve performance
gzip -k $MAIN
gzip -k $MAINCSS
gzip -k $MAINSVG
