#!/bin/sh

MAIN=`find /usr/share/nginx/html/static/js/main.*.js`
MAINCSS=`find /usr/share/nginx/html/static/css/main.*.css`
MAINSVG=`find /usr/share/nginx/html/static/media/*.svg`
echo -e "\nwindow.BASE_MAP='${REACT_APP_BASE_MAP}';" >> $MAIN
echo -e "window.MAP_STYLE='${REACT_APP_MAP_STYLE}';" >> $MAIN
echo -e "window.API_HOST='${REACT_APP_API_HOST}';" >> $MAIN
echo -e "window.GEOCODER_HOST='${REACT_APP_GEOCODER_HOST}';" >> $MAIN
echo -e "window.GEOCODER_API_AUTH_KEY='${REACT_APP_GEOCODER_API_AUTH_KEY}';" >> $MAIN
echo -e "window.ROUTE_PLANNER='${REACT_APP_ROUTE_PLANNER}';" >> $MAIN
echo -e "window.ROUTE_PLANNER_KEY='${REACT_APP_ROUTE_PLANNER_KEY}';" >> $MAIN
echo -e "window.REPLAY_THE_DAY='${REACT_APP_REPLAY_THE_DAY}';" >> $MAIN
echo -e "window.SURVEY_LINK='${REACT_APP_SURVEY_LINK}';" >> $MAIN

# Set the environment to be used for caching django content
sed -i "s~{ENVIRONMENT}~$ENVIRONMENT~g" /etc/nginx/conf.d/default.conf

#precompress the main js and css files to improve performance
gzip -k $MAIN
gzip -k $MAINCSS
gzip -k $MAINSVG
