fullnameOverride: django
nameOverride: django

replicaCount: 1

image:
  repository: ghcr.io/bcgov/drivebc-django
  tag: latest

deployment:
  resources:
    requests:
      cpu: 50m
      memory: 250Mi
  env:
    postgresSecret: drivebc-pguser-drivebc
    djangoConfigMap: drivebc-django
    djangoSecret: drivebc-django

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 75

route:
  host: drivebc.apps.silver.devops.gov.bc.ca
  iprestricted: false #Set to true if you want to limit IP's the the addresses in the ipallowlist below
  iprestrictedAdminPages: true
  ipallowlist: 142.34.53.0/24 142.22.0.0/15 142.24.0.0/13 142.32.0.0/13 208.181.128.46/32 #The first 4 ranges are GOV IP's, the last one is for OXD external IP

mediapvc:
  storage: 1Gi

apppvc:
  storage: 2Gi

podDisruptionBudget: 
  enabled: false #If you have more than 1 replica, you can set this to true.
  minAvailable: 1 