# Generated by Django 5.2.10 on 2026-01-26 21:10

import django.contrib.gis.db.models.fields
import django_prometheus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dms',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(blank=True, default='', max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('category', models.CharField(blank=True, default='', max_length=128)),
                ('description', models.CharField(blank=True, default='', max_length=750)),
                ('roadway_name', models.CharField(blank=True, default='', max_length=128)),
                ('roadway_direction', models.CharField(blank=True, default='', max_length=64)),
                ('static_text', models.CharField(blank=True, default='', max_length=256)),
                ('message_text', models.CharField(blank=True, default='', max_length=512)),
                ('status', models.CharField(blank=True, default='', max_length=64)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('updated_datetime_utc', models.DateTimeField(blank=True, null=True)),
                ('message_expiry_datetime_utc', models.DateTimeField(blank=True, null=True)),
                ('cache_datetime_utc', models.DateTimeField(blank=True, null=True)),
                ('message_display_1', models.TextField(blank=True, default='')),
                ('message_display_2', models.TextField(blank=True, default='')),
                ('message_display_3', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('dms'), models.Model),
        ),
    ]
