# Generated by Django 5.2.10 on 2026-01-23 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dms',
            name='location',
        ),
    ]
