# Generated by Django 5.2.10 on 2026-01-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dms',
            name='is_on',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dms',
            name='name_override',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
