# Generated by Django 5.2.10 on 2026-02-11 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dms',
            name='cache_datetime_utc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cache datetime'),
        ),
        migrations.AlterField(
            model_name='dms',
            name='is_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dms',
            name='message_expiry_datetime_utc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Message expiry datetime'),
        ),
        migrations.AlterField(
            model_name='dms',
            name='updated_datetime_utc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated datetime'),
        ),
    ]
