# Generated by Django 5.2.12 on 2026-03-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0002_alter_dms_cache_datetime_utc_alter_dms_is_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dms',
            name='status',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
