# Generated by Django 5.2.10 on 2026-01-23 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0002_remove_dms_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dms',
            name='feed_created_at',
        ),
        migrations.RemoveField(
            model_name='dms',
            name='feed_modified_at',
        ),
    ]
