# Generated by Django 5.2.10 on 2026-01-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0003_remove_dms_feed_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dms',
            name='id',
            field=models.CharField(blank=True, default='', max_length=128, primary_key=True, serialize=False),
        ),
    ]
