# Generated by Django 5.2.16 on 2026-09-11 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dms", "0003_alter_dms_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dms",
            name="is_on",
        ),
        migrations.RemoveField(
            model_name="dms",
            name="message_expiry_datetime_utc",
        ),
        migrations.RemoveField(
            model_name="dms",
            name="name_override",
        ),
        migrations.RemoveField(
            model_name="dms",
            name="static_text",
        ),
        migrations.RemoveField(
            model_name="dms",
            name="updated_datetime_utc",
        ),
    ]
