# Generated by Django 5.2.10 on 2026-01-23 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0004_alter_dms_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dms',
            name='message_display_1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dms',
            name='message_display_2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dms',
            name='message_display_3',
            field=models.TextField(blank=True, default=''),
        ),
    ]
