# Generated by Django 5.2.16 on 2026-09-18 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0004_remove_dms_is_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dms',
            name='cache_datetime_utc',
        ),
        migrations.AddField(
            model_name='dms',
            name='updated_datetime_utc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated datetime'),
        ),
    ]
