fullnameOverride: static
nameOverride: static

replicaCount: 1

image:
  repository: ghcr.io/bcgov/drivebc-static
  tag: latest-prod

release: 

deployment:
  resources:
    requests:
      cpu: 50m
      memory: 50Mi
  env:
    staticConfigMap: drivebc-static
  volumes:
    claimName: django-app-images

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 75

route:
  host: drivebc.apps.silver.devops.gov.bc.ca
  iprestricted: true #Set to true if you want to limit IP's the the addresses in the ipallowlist below
  ipallowlist: 142.34.53.0/24 142.22.0.0/15 142.24.0.0/13 142.32.0.0/13 208.181.128.46/32 #The first 4 ranges are GOV IP's, the last one is for OXD external IP

logpvc:
  storage: 1Gi

podDisruptionBudget: 
  enabled: false #If you have more than 1 replica, you can set this to true.
  minAvailable: 1 