# Generated by Django 4.2.1 on 2023-07-04 23:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("description", models.CharField(max_length=256)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("CONSTRUCTION", "Construction"),
                            ("INCIDENT", "Incident"),
                            ("SPECIAL_EVENT", "Special event"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "event_sub_type",
                    models.CharField(
                        choices=[
                            ("HAZARD", "Hazard"),
                            ("ROAD_CONSTRUCTION", "Road construction"),
                            ("ROAD_MAINTENANCE", "Road maintenance"),
                            ("PLANNED_EVENT", "Planned event"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(choices=[("ACTIVE", "Active")], max_length=32),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("Major", "Major"), ("Minor", "Minor")], max_length=32
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("N", "North"),
                            ("E", "East"),
                            ("S", "South"),
                            ("W", "West"),
                            ("BOTH", "Both"),
                            ("NONE", "None"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.LineStringField(srid=4326),
                ),
                ("route", models.CharField(max_length=128)),
                ("first_created", models.DateTimeField(null=True)),
                ("last_updated", models.DateTimeField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
