# Generated by Django 4.2.1 on 2023-07-05 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='first_created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='last_updated',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='severity',
            field=models.CharField(choices=[
                ('MAJOR', 'Major'), ('MINOR', 'Minor')
            ], max_length=32),
        ),
    ]
