# Generated by Django 4.2.1 on 2023-07-05 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_first_created_alter_event_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_sub_type',
            field=models.CharField(choices=[
                ('ALMOST_IMPASSABLE', 'Almost Impassable'),
                ('FIRE', 'Fire'),
                ('HAZARD', 'Hazard'),
                ('ROAD_CONSTRUCTION', 'Road construction'),
                ('ROAD_MAINTENANCE', 'Road maintenance'),
                ('PARTLY_ICY', 'Partly Icy'),
                ('PLANNED_EVENT', 'Planned event')
            ], max_length=32),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[
                ('CONSTRUCTION', 'Construction'),
                ('INCIDENT', 'Incident'),
                ('SPECIAL_EVENT', 'Special event'),
                ('WEATHER_CONDITION', 'Weather condition')
            ], max_length=32),
        ),
    ]
