# Generated by Django 4.2.1 on 2023-07-28 23:32

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_event_direction_alter_event_event_sub_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326),
        ),
    ]
