# Generated by Django 4.2.1 on 2023-08-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_event_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='route',
        ),
        migrations.AddField(
            model_name='event',
            name='route_at',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='route_from',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='route_to',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
