# Generated by Django 4.2.1 on 2023-09-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_remove_event_route_event_route_at_event_route_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_sub_type',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
