# Generated by Django 4.2.1 on 2023-09-28 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_alter_event_event_sub_type'),
        ('event', '0008_alter_event_route_at_alter_event_route_from_and_more'),
    ]

    operations = [
    ]
