# Generated by Django 4.2.3 on 2023-10-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_merge_20230928_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='schedule',
            field=models.JSONField(default={}),
        ),
    ]
