# Generated by Django 4.2.3 on 2024-01-08 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_event_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_sub_type',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
