# Generated by Django 4.2.3 on 2024-02-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_event_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='closest_landmark',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='event',
            name='highway_segment_names',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='event',
            name='location_description',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='event',
            name='next_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
