# Generated by Django 4.2.3 on 2024-03-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_alter_event_closest_landmark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='start_point_linear_reference',
            field=models.FloatField(null=True),
        ),
    ]
