# Generated by Django 4.2.16 on 2025-07-02 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_area'),
        ('event', '0021_event_display_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.area'),
        ),
    ]
