# Generated by Django 4.2.16 on 2025-07-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_area'),
        ('event', '0022_event_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='area',
        ),
        migrations.AddField(
            model_name='event',
            name='area',
            field=models.ManyToManyField(null=True, to='shared.area'),
        ),
    ]
