# Generated by Django 4.2.16 on 2025-07-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0023_remove_event_area_event_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='display_category',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
    ]
