# Generated by Django 4.2.22 on 2025-08-21 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_area'),
        ('event', '0024_alter_event_display_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='area',
            field=models.ManyToManyField(blank=True, to='shared.area'),
        ),
    ]
