# Generated by Django 4.2.22 on 2025-12-13 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0025_alter_event_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueuedEventNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('route_id', models.PositiveIntegerField()),
                ('event_id', models.CharField(max_length=32)),
            ],
            options={
                'unique_together': {('route_id', 'event_id')},
            },
        ),
    ]
