# Generated by Django 5.2.14 on 2026-06-29 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0026_queuedeventnotification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="closest_landmark",
            field=models.CharField(blank=True, default="", max_length=1024),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name="event",
            name="highway_segment_names",
            field=models.CharField(blank=True, default="", max_length=1024),
        ),
        migrations.AlterField(
            model_name="event",
            name="location_description",
            field=models.CharField(blank=True, default="", max_length=2048),
        ),
        migrations.AlterField(
            model_name="event",
            name="route_at",
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="event",
            name="route_from",
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="event",
            name="route_to",
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
