# Generated by Django 5.2.14 on 2026-07-09 23:05

import django_prometheus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0027_alter_event_closest_landmark_alter_event_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="QueuedDistrictEventNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("subscription_id", models.PositiveIntegerField()),
                ("event_ids", models.JSONField(blank=True, default=list)),
            ],
            options={
                "abstract": False,
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin(
                    "queued_district_event_notifications"
                ),
                models.Model,
            ),
        ),
    ]
