{{- $deploymentTag := .Values.image.tag | default .Chart.AppVersion -}}
{{- $deploymentTime := now | date "2006-01-02 15:04:05.000000" -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.fullname" . }}
  labels: {{ include "app.labels" . | nindent 4 }}
{{- if .Values.prometheus.enabled }}
annotations:
  prometheus.io/scrape: 'true'
  prometheus.io/port: '8000'
{{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{ include "app.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{ include "app.selectorLabels" . | nindent 8 }}
      annotations: 
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-secret-secrets.env: {{ .Values.global.vault.licenceplate }}-{{ .Values.global.vault.environment}}/{{ .Values.vault.secretName }}
        vault.hashicorp.com/agent-inject-template-secrets.env: |
          {{`{{- with secret `}}"{{ .Values.global.vault.licenceplate }}-{{ .Values.global.vault.environment }}/{{ .Values.vault.secretName }}"{{` }}
          {{- range $key, $value := .Data.data }}
          export {{$key}}="{{$value}}"
          {{- end }}
          {{- end `}} }}
        vault.hashicorp.com/agent-inject-token: 'false'
        vault.hashicorp.com/agent-pre-populate-only: 'true'
        vault.hashicorp.com/auth-path: {{ .Values.vault.authPath }}
        vault.hashicorp.com/namespace: platform-services
        vault.hashicorp.com/role: {{ .Values.global.vault.licenceplate }}-{{ .Values.global.vault.environment}}
    spec:
      volumes:
        - name: django-app-images-volume
          persistentVolumeClaim:
            claimName: {{ .Values.deployment.volumes.claimName  }}
      hostAliases: # DBC22-1527: This is a temporary workaround due to the fact that we can only access this IP for DIT from Gold.
        - ip: 142.34.81.128
          hostnames:
            - dit.th.gov.bc.ca
      containers:
        - resources:
            requests:
              cpu: {{ .Values.deployment.resources.requests.cpu  }}
              memory: {{ .Values.deployment.resources.requests.memory  }}
            limits:
              memory: {{ .Values.deployment.resources.limits.memory  }}
          name: {{ include "app.fullname" . }}
          command:
            - sh
            - '-c'
          args:
            - . /vault/secrets/secrets.env && /start_tasks.sh
          env:
            - name: DEPLOYMENT_TAG
              value: {{ $deploymentTag | quote }}
            - name: DEPLOYMENT_TIME
              value: {{ $deploymentTime | quote }}
            - name: RELEASE
              value: {{ .Values.global.release }}
            {{- range $key, $value := .Values.deployment.env.variables }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.deployment.env.postgresSecret  }}
                  key: host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.deployment.env.postgresSecret  }}
                  key: port
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.deployment.env.postgresSecret  }}
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.deployment.env.postgresSecret  }}
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.deployment.env.postgresSecret  }}
                  key: dbname
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: django-app-images-volume
              mountPath: /app/images/webcams
          imagePullPolicy: IfNotPresent
          image: >-
            {{ .Values.image.repository  }}:{{ .Values.image.tag  }}
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - '-c'
                - . /vault/secrets/secrets.env && python manage.py huey_health_check
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 3
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            runAsNonRoot: true
            allowPrivilegeEscalation: false
      serviceAccountName: {{ .Values.global.vault.licenceplate }}-vault
