# Generated by Django 4.2.16 on 2025-03-06 23:59

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.core.management import call_command
from django.db import migrations, models


def load_fixture(apps, schema_editor):
    call_command('loaddata', 'border_data.json')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BorderCrossing',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BorderCrossingLanes',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('lane_type', models.CharField(choices=[
                    ('Cars', 'Cars'), ('Bus', 'Bus'), ('FAST', 'FAST'), ('NEXUS', 'NEXUS'), ('Trucks', 'Trucks')
                ], max_length=64)),
                ('lane_direction', models.CharField(choices=[
                    ('NORTHBOUND', 'Northbound'), ('SOUTHBOUND', 'Southbound')
                ], max_length=64)),
                ('delay_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('border_crossing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='border.bordercrossing')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
