# Generated by Django 4.2.16 on 2025-03-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('border', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bordercrossinglanes',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
