# Generated by Django 4.2.16 on 2025-06-05 03:39

from django.core.management import call_command
from django.db import migrations, models


def load_fixture(apps, schema_editor):
    call_command('loaddata', 'border_data.json')


class Migration(migrations.Migration):

    dependencies = [
        ('border', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bordercrossing',
            name='schedule_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.RunPython(load_fixture),
    ]
