# Generated by Django 4.2.1 on 2023-08-29 18:16

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import wagtail.fields
import wagtail.search.index
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID'
                )),
                ('live', models.BooleanField(
                    default=True, editable=False, verbose_name='live'
                )),
                ('has_unpublished_changes', models.BooleanField(
                    default=False, editable=False,
                    verbose_name='has unpublished changes'
                )),
                ('first_published_at', models.DateTimeField(
                    blank=True, db_index=True, null=True,
                    verbose_name='first published at'
                )),
                ('last_published_at', models.DateTimeField(
                    editable=False, null=True, verbose_name='last published at'
                )),
                ('go_live_at', models.DateTimeField(
                    blank=True, null=True, verbose_name='go live date/time'
                )),
                ('expire_at', models.DateTimeField(
                    blank=True, null=True, verbose_name='expiry date/time'
                )),
                ('expired', models.BooleanField(
                    default=False, editable=False, verbose_name='expired'
                )),
                ('created_at', models.DateTimeField(
                    auto_now_add=True
                )),
                ('modified_at', models.DateTimeField(
                    auto_now=True
                )),
                ('name', models.CharField(max_length=64)),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=254)),
                ('url', models.URLField()),
                ('location_geometry',
                 django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('latest_revision', models.ForeignKey(
                    blank=True, editable=False, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='+', to='wagtailcore.revision',
                    verbose_name='latest revision'
                )),
                ('live_revision', models.ForeignKey(
                    blank=True, editable=False, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='+', to='wagtailcore.revision',
                    verbose_name='live revision'
                )),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
