# Generated by Django 4.2.1 on 2023-09-06 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FAQ',
            new_name='TestCMSData',
        ),
    ]
