# Generated by Django 4.2.3 on 2023-09-11 20:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('cms', '0002_rename_faq_testcmsdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisory',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('advisory_title', models.CharField(max_length=255)),
                ('advisory_active', models.BooleanField(default=True)),
                ('advisory_description', wagtail.fields.RichTextField(blank=True)),
                ('advisory_geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
