# Generated by Django 4.2.3 on 2023-10-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_bulletin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advisory',
            old_name='description',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='bulletin',
            old_name='description',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='advisory',
            name='active',
        ),
        migrations.RemoveField(
            model_name='bulletin',
            name='active',
        ),
        migrations.AddField(
            model_name='advisory',
            name='teaser',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='teaser',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
