# Generated by Django 4.2.3 on 2023-11-02 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('cms', '0007_rename_description_advisory_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletin',
            name='image',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='wagtailimages.image'
            ),
        ),
    ]
