# Generated by Django 4.2.3 on 2023-11-22 00:48

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('cms', '0008_bulletin_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ferry',
            fields=[
                ('page_ptr', models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True, primary_key=True, serialize=False,
                    to='wagtailcore.page'
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('location', django.contrib.gis.db.models.fields.GeometryField(
                    srid=4326
                )),
                ('url', models.URLField(blank=True)),
                ('description', wagtail.fields.RichTextField(
                    blank=True, max_length=750
                )),
                ('seasonal_description', wagtail.fields.RichTextField(
                    blank=True, max_length=100
                )),
                ('service_hours', wagtail.fields.RichTextField(
                    blank=True, max_length=750
                )),
                ('feed_created_at', models.DateTimeField()),
                ('feed_modified_at', models.DateTimeField()),
                ('image', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    to='wagtailimages.image'
                )),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
