# Generated by Django 4.2.3 on 2023-11-22 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_ferry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ferry',
            name='feed_created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ferry',
            name='feed_modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
