# Generated by Django 4.2.3 on 2023-11-24 01:05

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_alter_ferry_feed_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ferry',
            name='location',
            field=django.contrib.gis.db.models.fields.GeometryField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
