# Generated by Django 4.2.3 on 2023-11-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_alter_ferry_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferry',
            name='feed_id',
            field=models.PositiveIntegerField(default=None, unique=True),
            preserve_default=False,
        ),
    ]
