# Generated by Django 4.2.3 on 2023-12-27 19:07

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('cms', '0012_ferry_feed_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisory',
            name='body',
            field=wagtail.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='body',
            field=wagtail.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='image',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='wagtailimages.image'
            ),
        ),
    ]
