# Generated by Django 4.2.3 on 2024-02-14 14:45

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_bulletin_image_alt_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisory',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
        ),
    ]
