# Generated by Django 4.2.3 on 2024-05-17 19:45

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_alter_bulletin_image_alter_ferry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisory',
            name='geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
