# Generated by Django 4.2.16 on 2024-11-15 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_alter_advisory_options_alter_ferry_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ferry',
        ),
    ]
