# Generated by Django 4.2.16 on 2025-01-29 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_subpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulletin',
            options={'verbose_name_plural': 'bulletins'},
        ),
    ]
