# Generated by Django 4.2.16 on 2025-06-23 22:34

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('cms', '0022_alter_bulletin_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('alert', wagtail.fields.RichTextField(max_length=90)),
                ('body', wagtail.fields.StreamField([('subheading', 0), ('rich_text', 1), ('table', 2), ('callout', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'template': 'cms/subheading.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'table_options': {'colHeaders': True, 'rowHeaders': True}}), 3: ('wagtail.blocks.RichTextBlock', (), {'help_text': "\nThis block is for information that needs to be presented as especially important,\nstyled according to the BC gov't's style guide (light grey background, blue\nborder on the left).\n", 'template': 'cms/callout.html'})})),
            ],
            options={
                'verbose_name_plural': 'Emergency Alert',
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
