# Generated by Django 5.2.12 on 2026-03-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_emergencyalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisory',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='Lower = higher priority'),
        ),
    ]
