# Generated by Django 5.2.12 on 2026-03-16 17:16

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_emergencyalert'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    wagtailcore_page = 'wagtailcore.page'

    operations = [
        migrations.CreateModel(
            name='EmergencyAlertDetail',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=wagtailcore_page)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('body', wagtail.fields.StreamField([('subheading', 0), ('rich_text', 1), ('table', 2), ('callout', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'template': 'cms/subheading.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'table_options': {'colHeaders': True, 'rowHeaders': True}}), 3: ('wagtail.blocks.RichTextBlock', (), {'help_text': "\nThis block is for information that needs to be presented as especially important,\nstyled according to the BC gov't's style guide (light grey background, blue\nborder on the left).\n", 'template': 'cms/callout.html'})})),
            ],
            options={
                'verbose_name': 'Emergency Alert Detail',
                'verbose_name_plural': 'Emergency Alert Details',
            },
            bases=(wagtailcore_page, models.Model),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='detail_page',
            field=models.ForeignKey(blank=True, help_text='Optional: link to an Emergency Alert detail page shown to the public.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=wagtailcore_page),
        ),
    ]
