# Generated by Django 5.2.12 on 2026-03-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0024_advisory_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletin',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='Lower = higher priority'),
        ),
    ]
