# Generated by Django 5.2.14 on 2026-06-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0025_advisoryindexpage_bulletinindexpage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisory',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
