# Generated by Django 4.2.3 on 2024-04-23 23:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteGeometry',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('routes', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
    ]
