# Generated by Django 4.2.22 on 2025-08-29 18:31

# from apps.shared.tasks import populate_all_district_data
from django.db import migrations


def populate_areas(apps, schema_editor):
    # populate_all_district_data()
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_area'),
    ]

    operations = [
        migrations.RunPython(populate_areas),
    ]
