# Generated by Django 4.2.16 on 2025-07-07 20:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wildfire',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('url', models.URLField(blank=True, null=True)),
                ('name', models.CharField(max_length=256)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('size', models.FloatField()),
                ('status', models.CharField(max_length=128)),
                ('reported_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
