# Generated by Django 4.2.22 on 2025-09-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildfire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wildfire',
            name='name',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
