# Generated by Django 5.2.14 on 2026-07-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wildfire", "0003_alter_wildfire_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="wildfire",
            name="wildfire_of_note",
            field=models.BooleanField(default=False),
        ),
    ]
