

fullnameOverride: openshiftjobs
nameOverride: openshiftjobs

image:
  repository: ghcr.io/bcgov/drivebc-openshiftjobs
  tag: latest

cronjobs:
  backupmediapvc:
    name: backupmediapvc
    schedule: '0 8 * * *'
    deployment:
      resources:
        requests:
          cpu: 50m
          memory: 100Mi
      env:
        s3Secret: drivebc-cronjob-s3bucket
      volumes:
        media: django
