{{- $deploymentTag := .Values.image.tag | default .Chart.AppVersion -}}
{{- $deploymentTime := now | date "2006-01-02 15:04:05.000000" -}}
{{- if .Values.cronjobs.ziplogs.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ template "app.fullname" . }}-{{ .Values.cronjobs.ziplogs.name }}
  labels: {{ include "app.labels" . | nindent 4 }}

spec:
  schedule: {{ .Values.cronjobs.ziplogs.schedule }}
  concurrencyPolicy: Replace
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: log-storage
              persistentVolumeClaim:
                claimName: {{ .Values.cronjobs.ziplogs.deployment.volumes.logs  }}
          containers:
            - resources:
                requests:
                  cpu: {{ .Values.cronjobs.ziplogs.deployment.resources.requests.cpu  }}
                  memory: {{ .Values.cronjobs.ziplogs.deployment.resources.requests.memory  }}
                limits:
                  memory: {{ .Values.cronjobs.ziplogs.deployment.resources.limits.memory  }}
              name: {{ include "app.fullname" . }}-{{ .Values.cronjobs.ziplogs.name }}
              args:
                - "ziplogs"
              volumeMounts:
                - name: log-storage
                  mountPath: /logs
              env:
                - name: DEPLOYMENT_TAG
                  value: {{ $deploymentTag | quote }}
                - name: DEPLOYMENT_TIME
                  value: {{ $deploymentTime | quote }}
                - name: RELEASE
                  value: {{ .Values.global.release }}
                {{- range $key, $value := .Values.cronjobs.analyzeuploadlogs.deployment.env.variables }}
                - name: {{ $key }}
                  value: {{ $value | quote }}
                {{- end }}
              imagePullPolicy: IfNotPresent
              image: {{ .Values.image.repository  }}:{{ .Values.image.tag  }}
              securityContext:
                seccompProfile:
                  type: 'RuntimeDefault'
                runAsNonRoot: true
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - all
                  add:
                    - NET_BIND_SERVICE
          restartPolicy: Never
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
{{- end }}