nameOverride: uat-drivebc
fullnameOverride: uat-drivebc

django:
  fullnameOverride: uat-django
  nameOverride: uat-django
  replicaCount: 3
  image:
    repository: ghcr.io/bcgov/drivebc-django
    tag: latest-uat
  deployment:
    resources:
      requests:
        cpu: 50m
        memory: 300Mi
    env:
      postgresSecret: uat-drivebc-db-pguser-uat-drivebc-db
      djangoConfigMap: uat-drivebc-django
      djangoSecret: uat-drivebc-django
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 5
    targetCPUUtilizationPercentage: 200
  route:
    host: uat-drivebc.apps.gold.devops.gov.bc.ca
    iprestricted: true #Set to true if you want to limit IP's that can access publicly available pages to the the addresses in the ipallowlist 
    iprestrictedAdminPages: true #Set to true if you want to limit IP's that can access backend admin pages
  mediapvc:
    storage: 1Gi
  apppvc:
    storage: 1Gi
  podDisruptionBudget: 
    enabled: true 
    minAvailable: 1

tasks:
  fullnameOverride: uat-tasks
  nameOverride: uat-tasks
  replicaCount: 1
  image:
    repository: ghcr.io/bcgov/drivebc-django
    tag: latest-uat
  deployment:
    resources:
      requests:
        cpu: 200m
        memory: 250Mi
    volumes:
      claimName: uat-django-app-images
    env:
      postgresSecret: uat-drivebc-db-pguser-uat-drivebc-db
      djangoConfigMap: uat-drivebc-django
      djangoSecret: uat-drivebc-django

redis:
  fullnameOverride: uat-redis
  nameOverride: uat-redis
  replicaCount: 1
  image:
    repository: ghcr.io/bcgov/drivebc-redis
    tag: latest-uat
  deployment:
    resources:
      requests:
        cpu: 50m
        memory: 50Mi

static:
  fullnameOverride: uat-static
  nameOverride: uat-static
  replicaCount: 3
  release:   
  image:
    repository: ghcr.io/bcgov/drivebc-static
    tag: latest-uat
  deployment:
    resources:
      requests:
        cpu: 50m
        memory: 50Mi
    env:
      staticConfigMap: uat-drivebc-static
    volumes:
      imagesClaimName: uat-django-app-images
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 5
    targetCPUUtilizationPercentage: 200
  route:
    host: uat-drivebc.apps.gold.devops.gov.bc.ca
    iprestricted: true  #Set to true if you want to limit IP's the the addresses in the ipallowlist 
  logpvc:
    storage: 5Gi
  podDisruptionBudget: 
    enabled: true 
    minAvailable: 1

openshiftjobs:
  fullnameOverride: uat-openshiftjobs
  nameOverride: uat-openshiftjobs

  image:
    repository: ghcr.io/bcgov/drivebc-openshiftjobs
    tag: latest-uat

  cronjobs:
    analyzeuploadlogs:
      name: analyzeuploadlogs
      schedule: '0 9 * * *'  #NOTE: This is in UTC
      deployment:
        resources:
          requests:
            cpu: 50m
            memory: 150Mi
        env:
          s3Secret: uat-drivebc-cronjob-s3bucket
        volumes:
          logs: uat-static-log-storage

    ziplogs:
      name: ziplogs
      schedule: '30 * * * *'
      deployment:
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
        volumes:
          logs: uat-static-log-storage

    backupmediapvc:
      name: backupmediapvc
      schedule: '0 8 * * *'
      deployment:
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
        env:
          s3Secret: uat-drivebc-cronjob-s3bucket
        volumes:
          media: uat-django