import os
from sqlalchemy import create_engine, text
from sqlalchemy.engine import URL
from apps.consumer.models import ImageIndex
from asgiref.sync import sync_to_async

# Connection settings
SQL_DB_SERVER = os.getenv("SQL_DB_SERVER", "sql-server-db")
SQL_DB_NAME = os.getenv("SQL_DB_NAME", "camera-db")
SQL_DB_USER = os.getenv("SQL_DB_USER", "sa")
SQL_DB_PASSWORD = os.getenv("SQL_DB_PASSWORD", "YourStrong@Passw0rd")
SQL_DB_DRIVER = "ODBC Driver 17 for SQL Server"  # Make sure this driver is installed on the container

# Build connection URL
connection_url = URL.create(
    "mssql+pyodbc",
    username=SQL_DB_USER,
    password=SQL_DB_PASSWORD,
    host=SQL_DB_SERVER,
    port=1433,
    database=SQL_DB_NAME,
    query={"driver": SQL_DB_DRIVER}
)

# Create SQLAlchemy engine
engine = create_engine(connection_url)

def get_all_from_db():
    cams_sql = """
        SELECT [ID]
        ,[Cam_InternetName]
        ,[Cam_InternetCaption]
        ,[Cam_InternetCredit]
        ,[Cam_InternetComments]
        ,[Cam_InternetWebsite_URL]
        ,[Cam_InternetGetfile2_URL]
        ,[Cam_InternetDriveBC_URL]
        ,[Cam_InternetFTP_Path]
        ,[Cam_InternetFTP_Folder]
        ,[Cam_InternetFTP_Filename]
        ,[Cam_InternetDisplay_Folder]
        ,[Cam_InternetDisplay_Filename]
        ,[Cam_InternetContact_Notes]
        ,[Cam_InternetDBC_Mark]
        ,[Cam_InternetInset_Horizontal]
        ,[Cam_InternetUpdated_By]
        ,[Cam_InternetLast_Updated]
        ,[Cam_LocationsRegion]
        ,[Cam_LocationsBusiness_Area]
        ,[Cam_LocationsHighway]
        ,[Cam_LocationsHighway_Section]
        ,[Cam_LocationsOrientation]
        ,[Cam_LocationsLandmark]
        ,[Cam_LocationsCrossroad]
        ,[Cam_LocationsElevation]
        ,[Cam_LocationsCam_Group]
        ,[Cam_LocationsGeo_Latitude]
        ,[Cam_LocationsGeo_Longitude]
        ,[Cam_LocationsAlbers_Northing]
        ,[Cam_LocationsAlbers_Easting]
        ,[Cam_LocationsSegment]
        ,[Cam_LocationsLRS_Node]
        ,[Cam_LocationsDD]
        ,[Cam_LocationsMap_Art_No]
        ,[Cam_LocationsThumbnail_Map_URL]
        ,[Cam_LocationsRegional_Map_URL]
        ,[Cam_LocationsUpdated_By]
        ,[Cam_LocationsLast_Updated]
        ,[Cam_LocationsWeather_Station]
        ,[Cam_LocationsForecast_ID]
        ,[Cam_MaintenanceAsset_No]
        ,[Cam_MaintenanceCamera_Make]
        ,[Cam_MaintenanceSN]
        ,[Cam_MaintenanceLocal_IP]
        ,[Cam_MaintenanceCredentials]
        ,[Cam_MaintenancePublic_IP]
        ,[Cam_MaintenanceUpload_Image]
        ,[Cam_MaintenanceUploads_Every]
        ,[Cam_MaintenanceLink_Check]
        ,[Cam_MaintenanceComm_Tech]
        ,[Cam_MaintenanceComm_Device]
        ,[Cam_MaintenanceService_Provider]
        ,[Cam_MaintenanceModem_IP]
        ,[Cam_MaintenanceSignal]
        ,[Cam_MaintenanceModem_ESN]
        ,[Cam_MaintenanceMSL]
        ,[Cam_MaintenanceAntennae]
        ,[Cam_MaintenanceModem_Phone]
        ,[Cam_MaintenancePS_SN]
        ,[Cam_MaintenanceBaud_Rate]
        ,[Cam_MaintenanceMonth_Implemented]
        ,[Cam_MaintenanceDay_Implemented]
        ,[Cam_MaintenanceYear_Implemented]
        ,[Cam_MaintenanceMonth_Installed]
        ,[Cam_MaintenanceDay_Installed]
        ,[Cam_MaintenanceYear_Installed]
        ,[Cam_MaintenanceMonth_Modem]
        ,[Cam_MaintenanceDay_Modem]
        ,[Cam_MaintenanceYear_Modem]
        ,[Cam_MaintenanceSignal_Strength]
        ,[Cam_MaintenanceOwner]
        ,[Cam_MaintenanceAlternate_Owner]
        ,[Cam_MaintenanceMaint_Notes]
        ,[Cam_MaintenanceNotes]
        ,[Cam_MaintenanceHardware_Notes]
        ,[Cam_MaintenanceUpdated_By]
        ,[Cam_MaintenanceLast_Updated]
        ,[Cam_HydroPower_Source]
        ,[Cam_HydroIssues]
        ,[Cam_HydroTechnical_Contact]
        ,[Cam_HydroTechnical_Contact_Phone]
        ,[Cam_HydroOther_Contact]
        ,[Cam_HydroOther_Contact_Phone]
        ,[Cam_HydroPole_No]
        ,[Cam_HydroTag_No]
        ,[Cam_HydroPower_Outages]
        ,[Cam_HydroLast_Updated]
        ,[Cam_HydroUpdated_By]
        ,[Cam_InstallationStatus]
        ,[Cam_InstallationActivation_Month]
        ,[Cam_InstallationActivation_Day]
        ,[Cam_InstallationActivation_Year]
        ,[Cam_InstallationDate_Approximate]
        ,[Cam_InstallationInstaller]
        ,[Cam_InstallationOther]
        ,[Cam_InstallationShared_Installation]
        ,[Cam_InstallationShared_Maint]
        ,[Cam_InstallationSharing_Comments]
        ,[Cam_InstallationOwner]
        ,[Cam_InstallationMOT_Contact]
        ,[Cam_InstallationPartnership_Wording]
        ,[Cam_InstallationApprox_Install_Cost]
        ,[Cam_InstallationFed_Funding]
        ,[Cam_InstallationOther_Funding]
        ,[Cam_InstallationTotal_Funding]
        ,[Cam_InstallationTechnical_Issues]
        ,[Cam_InstallationCommunity_Issues]
        ,[Cam_InstallationOther_Comments]
        ,[Cam_InstallationNews_Link]
        ,[Cam_InstallationUpdated_By]
        ,[Cam_InstallationLast_Updated]
        ,[Cam_CommunicationType]
        ,[Cam_CommunicationProvider]
        ,[Cam_CommunicationBAN]
        ,[Cam_CommunicationDept_Code]
        ,[Cam_CommunicationConfiguration]
        ,[Cam_CommunicationBusiness_Contact]
        ,[Cam_CommunicationBusiness_Phone]
        ,[Cam_CommunicationBilling_Address]
        ,[Cam_CommunicationUsage_Plan]
        ,[Cam_CommunicationModem_Cell_No]
        ,[Cam_CommunicationModem_Location]
        ,[Cam_CommunicationESN]
        ,[Cam_CommunicationComm_Tech]
        ,[Cam_CommunicationComm_Device]
        ,[Cam_CommunicationPublic_IP]
        ,[Cam_CommunicationSL]
        ,[Cam_CommunicationMSL]
        ,[Cam_CommunicationNumber]
        ,[Cam_CommunicationDynamic_or_Static]
        ,[Cam_CommunicationBaud_Rate]
        ,[Cam_CommunicationModem_Admin_IP]
        ,[Cam_CommunicationModem_ESN]
        ,[Cam_CommunicationActivation_Month]
        ,[Cam_CommunicationActivation_Day]
        ,[Cam_CommunicationActivation_Year]
        ,[Cam_CommunicationStation_Name]
        ,[Cam_CommunicationStation_Description]
        ,[Cam_CommunicationTechnical_Contact]
        ,[Cam_CommunicationSignal_Strength]
        ,[Cam_CommunicationNotes]
        ,[Cam_CommunicationUpdated_By]
        ,[Cam_CommunicationLast_Updated]
        ,[Cam_FTPUpdated_By]
        ,[Cam_FTPLast_Updated]
        ,[Cam_ControlNotes]
        ,[Cam_ControlShort_Message]
        ,[Cam_ControlLong_Message]
        
        ,[Cam_ControlDisappear]
        ,[Cam_ControlTimeout1]
        ,[Cam_Controltimeout2]
        ,[Cam_ControlOff_Time]
        ,[Cam_ControlOff_Duration]
        ,[Cam_ControlOff_Message_Short]
        ,[Cam_ControlOff_Message_Long]
        ,[Cam_ControlAuto_Off]
        ,[seq]
        ,[Cam_InternetMap_Coords]
        ,[Cam_InternetMap_Shape]
        ,[Cam_InternetMap_Jpeg]
        ,[Cam_InternetMap_ID]
        ,[Cam_ControlOCC]
        ,[Cam_ControlResize_Mode]
        ,[isNew]
        ,[Cam_InternetOn_Demand_URL]
        ,[Cam_InternetOn_Demand_Username]
        ,[Cam_InternetOn_Demand_Password]
        ,[Cam_On_DemandUpdated_By]
        ,[Cam_On_DemandLast_Updated]
        ,[Cam_MaintenanceIs_On_Demand]
        ,[upsize_ts]
        FROM [WEBCAM_DEV].[dbo].[Cams]
    """

    cams_live_sql = """
        SELECT [ID]
        ,[Cam_InternetName]
        ,[Cam_InternetCaption]
        ,[Cam_InternetCredit]
        ,[Cam_InternetComments]
        ,[Cam_InternetWebsite_URL]
        ,[Cam_InternetGetfile2_URL]
        ,[Cam_InternetDriveBC_URL]
        ,[Cam_InternetFTP_Path]
        ,[Cam_InternetFTP_Folder]
        ,[Cam_InternetFTP_Filename]
        ,[Cam_InternetDisplay_Folder]
        ,[Cam_InternetDisplay_Filename]
        ,[Cam_InternetContact_Notes]
        ,[Cam_InternetDBC_Mark]
        ,[Cam_InternetInset_Horizontal]
        ,[Cam_InternetUpdated_By]
        ,[Cam_InternetLast_Updated]
        ,[Cam_LocationsRegion]
        ,[Cam_LocationsBusiness_Area]
        ,[Cam_LocationsHighway]
        ,[Cam_LocationsHighway_Section]
        ,[Cam_LocationsOrientation]
        ,[Cam_LocationsLandmark]
        ,[Cam_LocationsCrossroad]
        ,[Cam_LocationsElevation]
        ,[Cam_LocationsCam_Group]
        ,[Cam_LocationsGeo_Latitude]
        ,[Cam_LocationsGeo_Longitude]
        ,[Cam_LocationsAlbers_Northing]
        ,[Cam_LocationsAlbers_Easting]
        ,[Cam_LocationsSegment]
        ,[Cam_LocationsLRS_Node]
        ,[Cam_LocationsDD]
        ,[Cam_LocationsMap_Art_No]
        ,[Cam_LocationsThumbnail_Map_URL]
        ,[Cam_LocationsRegional_Map_URL]
        ,[Cam_LocationsUpdated_By]
        ,[Cam_LocationsLast_Updated]
        ,[Cam_LocationsWeather_Station]
        ,[Cam_LocationsForecast_ID]
        ,[Cam_MaintenanceAsset_No]
        ,[Cam_MaintenanceCamera_Make]
        ,[Cam_MaintenanceSN]
        ,[Cam_MaintenanceLocal_IP]
        ,[Cam_MaintenanceCredentials]
        ,[Cam_MaintenancePublic_IP]
        ,[Cam_MaintenanceUpload_Image]
        ,[Cam_MaintenanceUploads_Every]
        ,[Cam_MaintenanceLink_Check]
        ,[Cam_MaintenanceComm_Tech]
        ,[Cam_MaintenanceComm_Device]
        ,[Cam_MaintenanceService_Provider]
        ,[Cam_MaintenanceModem_IP]
        ,[Cam_MaintenanceSignal]
        ,[Cam_MaintenanceModem_ESN]
        ,[Cam_MaintenanceMSL]
        ,[Cam_MaintenanceAntennae]
        ,[Cam_MaintenanceModem_Phone]
        ,[Cam_MaintenancePS_SN]
        ,[Cam_MaintenanceBaud_Rate]
        ,[Cam_MaintenanceMonth_Implemented]
        ,[Cam_MaintenanceDay_Implemented]
        ,[Cam_MaintenanceYear_Implemented]
        ,[Cam_MaintenanceMonth_Installed]
        ,[Cam_MaintenanceDay_Installed]
        ,[Cam_MaintenanceYear_Installed]
        ,[Cam_MaintenanceMonth_Modem]
        ,[Cam_MaintenanceDay_Modem]
        ,[Cam_MaintenanceYear_Modem]
        ,[Cam_MaintenanceSignal_Strength]
        ,[Cam_MaintenanceOwner]
        ,[Cam_MaintenanceAlternate_Owner]
        ,[Cam_MaintenanceMaint_Notes]
        ,[Cam_MaintenanceNotes]
        ,[Cam_MaintenanceHardware_Notes]
        ,[Cam_MaintenanceUpdated_By]
        ,[Cam_MaintenanceLast_Updated]
        ,[Cam_HydroPower_Source]
        ,[Cam_HydroIssues]
        ,[Cam_HydroTechnical_Contact]
        ,[Cam_HydroTechnical_Contact_Phone]
        ,[Cam_HydroOther_Contact]
        ,[Cam_HydroOther_Contact_Phone]
        ,[Cam_HydroPole_No]
        ,[Cam_HydroTag_No]
        ,[Cam_HydroPower_Outages]
        ,[Cam_HydroLast_Updated]
        ,[Cam_HydroUpdated_By]
        ,[Cam_InstallationStatus]
        ,[Cam_InstallationActivation_Month]
        ,[Cam_InstallationActivation_Day]
        ,[Cam_InstallationActivation_Year]
        ,[Cam_InstallationDate_Approximate]
        ,[Cam_InstallationInstaller]
        ,[Cam_InstallationOther]
        ,[Cam_InstallationShared_Installation]
        ,[Cam_InstallationShared_Maint]
        ,[Cam_InstallationSharing_Comments]
        ,[Cam_InstallationOwner]
        ,[Cam_InstallationMOT_Contact]
        ,[Cam_InstallationPartnership_Wording]
        ,[Cam_InstallationApprox_Install_Cost]
        ,[Cam_InstallationFed_Funding]
        ,[Cam_InstallationOther_Funding]
        ,[Cam_InstallationTotal_Funding]
        ,[Cam_InstallationTechnical_Issues]
        ,[Cam_InstallationCommunity_Issues]
        ,[Cam_InstallationOther_Comments]
        ,[Cam_InstallationNews_Link]
        ,[Cam_InstallationUpdated_By]
        ,[Cam_InstallationLast_Updated]
        ,[Cam_CommunicationType]
        ,[Cam_CommunicationProvider]
        ,[Cam_CommunicationBAN]
        ,[Cam_CommunicationDept_Code]
        ,[Cam_CommunicationConfiguration]
        ,[Cam_CommunicationBusiness_Contact]
        ,[Cam_CommunicationBusiness_Phone]
        ,[Cam_CommunicationBilling_Address]
        ,[Cam_CommunicationUsage_Plan]
        ,[Cam_CommunicationModem_Cell_No]
        ,[Cam_CommunicationModem_Location]
        ,[Cam_CommunicationESN]
        ,[Cam_CommunicationComm_Tech]
        ,[Cam_CommunicationComm_Device]
        ,[Cam_CommunicationPublic_IP]
        ,[Cam_CommunicationSL]
        ,[Cam_CommunicationMSL]
        ,[Cam_CommunicationNumber]
        ,[Cam_CommunicationDynamic_or_Static]
        ,[Cam_CommunicationBaud_Rate]
        ,[Cam_CommunicationModem_Admin_IP]
        ,[Cam_CommunicationModem_ESN]
        ,[Cam_CommunicationActivation_Month]
        ,[Cam_CommunicationActivation_Day]
        ,[Cam_CommunicationActivation_Year]
        ,[Cam_CommunicationStation_Name]
        ,[Cam_CommunicationStation_Description]
        ,[Cam_CommunicationTechnical_Contact]
        ,[Cam_CommunicationSignal_Strength]
        ,[Cam_CommunicationNotes]
        ,[Cam_CommunicationUpdated_By]
        ,[Cam_CommunicationLast_Updated]
        ,[Cam_FTPUpdated_By]
        ,[Cam_FTPLast_Updated]
        ,[Cam_ControlNotes]
        ,[Cam_ControlShort_Message]
        ,[Cam_ControlLong_Message]
        ,[Cam_ControlDisabled]
        ,[Cam_ControlDisappear]
        ,[Cam_ControlTimeout1]
        ,[Cam_Controltimeout2]
        ,[Cam_ControlOff_Time]
        ,[Cam_ControlOff_Duration]
        ,[Cam_ControlOff_Message_Short]
        ,[Cam_ControlOff_Message_Long]
        ,[Cam_ControlAuto_Off]
        ,[seq]
        ,[Cam_InternetMap_Coords]
        ,[Cam_InternetMap_Shape]
        ,[Cam_InternetMap_Jpeg]
        ,[Cam_InternetMap_ID]
        ,[Cam_ControlOCC]
        ,[Cam_ControlResize_Mode]
        ,[isNew]
        ,[Cam_InternetOn_Demand_URL]
        ,[Cam_InternetOn_Demand_Username]
        ,[Cam_InternetOn_Demand_Password]
        ,[Cam_On_DemandUpdated_By]
        ,[Cam_On_DemandLast_Updated]
        ,[Cam_MaintenanceIs_On_Demand]
        ,[upsize_ts]
        FROM [WEBCAM_DEV].[dbo].[Cams_Live]
    """

    with engine.connect() as connection:
        try:
            # Query from Cams
            result_cams = connection.execute(text(cams_sql))
            cams_rows = {row.ID: dict(row._mapping) for row in result_cams}

            # Query from Cams_Live
            result_live = connection.execute(text(cams_live_sql))
            live_rows = {row.ID: dict(row._mapping) for row in result_live}

            # Merge based on ID
            merged_rows = []
            for cam_id, cam_data in cams_rows.items():
                live_data = live_rows.get(cam_id, {})
                merged_row = {**cam_data, **live_data}
                merged_rows.append(merged_row)

            return merged_rows

        except Exception as e:
            print(f"Failed to connect to the database: {e}")
            return []

@sync_to_async
def load_index_from_db():
    records = ImageIndex.objects.order_by('timestamp').all()

    index_db = [
        {
            "camera_id": record.camera_id,
            "timestamp": record.timestamp,
        }
        for record in records
    ]

    return index_db