class EVENT_TYPE:
    CONSTRUCTION = "CONSTRUCTION"
    INCIDENT = "INCIDENT"
    SPECIAL_EVENT = "SPECIAL_EVENT"
    WEATHER_CONDITION = "WEATHER_CONDITION"


EVENT_TYPE_CHOICES = (
    (EVENT_TYPE.CONSTRUCTION, "Construction"),
    (EVENT_TYPE.INCIDENT, "Incident"),
    (EVENT_TYPE.SPECIAL_EVENT, "Special event"),
    (EVENT_TYPE.WEATHER_CONDITION, "Weather condition"),
)


class EVENT_SUB_TYPE:
    ALMOST_IMPASSABLE = "ALMOST_IMPASSABLE"
    FIRE = "FIRE"
    HAZARD = "HAZARD"
    ROAD_CONSTRUCTION = "ROAD_CONSTRUCTION"
    ROAD_MAINTENANCE = "ROAD_MAINTENANCE"
    PARTLY_ICY = "PARTLY_ICY"
    PLANNED_EVENT = "PLANNED_EVENT"


EVENT_SUB_TYPE_CHOICES = (
    (EVENT_SUB_TYPE.ALMOST_IMPASSABLE, "Almost Impassable"),
    (EVENT_SUB_TYPE.FIRE, "Fire"),
    (EVENT_SUB_TYPE.HAZARD, "Hazard"),
    (EVENT_SUB_TYPE.ROAD_CONSTRUCTION, "Road construction"),
    (EVENT_SUB_TYPE.ROAD_MAINTENANCE, "Road maintenance"),
    (EVENT_SUB_TYPE.PARTLY_ICY, "Partly Icy"),
    (EVENT_SUB_TYPE.PLANNED_EVENT, "Planned event"),
)


class EVENT_STATUS:
    ACTIVE = "ACTIVE"


EVENT_STATUS_CHOICES = ((EVENT_STATUS.ACTIVE, "Active"),)


class EVENT_SEVERITY:
    MAJOR = "MAJOR"
    MINOR = "MINOR"


EVENT_SEVERITY_CHOICES = (
    (EVENT_SEVERITY.MAJOR, "Major"),
    (EVENT_SEVERITY.MINOR, "Minor"),
)


class EVENT_DIRECTION:
    NORTH = "N"
    EAST = "E"
    SOUTH = "S"
    WEST = "W"
    BOTH = "BOTH"
    NONE = "NONE"


EVENT_DIRECTION_CHOICES = (
    (EVENT_DIRECTION.NORTH, "North"),
    (EVENT_DIRECTION.EAST, "East"),
    (EVENT_DIRECTION.SOUTH, "South"),
    (EVENT_DIRECTION.WEST, "West"),
    (EVENT_DIRECTION.BOTH, "Both"),
    (EVENT_DIRECTION.NONE, "None"),
)
