apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "app.fullname" . }}-frontend
  labels: {{ include "app.labels" . | nindent 4 }}
  annotations:
    {{ if .Values.route.iprestricted }}
    haproxy.router.openshift.io/ip_whitelist: {{ .Values.global.route.ipallowlist  }}
    {{ end }}
    haproxy.router.openshift.io/disable_cookies: 'true'
spec:
  host: {{ .Values.route.host  }} 
  to:
    kind: Service
    name: {{ template "app.fullname" . }}-frontend
  port:
    targetPort: 3000
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None

---
{{- if .Values.route.vanityurl.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "app.fullname" . }}-frontend-vanityurl
  labels: {{ include "app.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
    haproxy.router.openshift.io/disable_cookies: 'true'
    {{ if .Values.route.iprestricted }}
    haproxy.router.openshift.io/ip_whitelist: {{ .Values.global.route.ipallowlist  }}
    {{ end }}
spec:
  host: {{ .Values.route.vanityurl.vanityurlhost  }}
  to:
    kind: Service
    name: {{ template "app.fullname" . }}-frontend
  port:
    targetPort: 3000
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
{{- end }}

---
{{- if .Values.route.vanityurl.extravanityurlhost }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "app.fullname" . }}-frontend-nonwww-vanityurl
  labels: {{ include "app.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
    haproxy.router.openshift.io/disable_cookies: 'true'
    {{ if .Values.route.iprestricted }}
    haproxy.router.openshift.io/ip_whitelist: {{ .Values.global.route.ipallowlist  }}
    {{ end }}
spec:
  host: {{ .Values.route.vanityurl.extravanityurlhost  }}
  to:
    kind: Service
    name: {{ template "app.fullname" . }}-frontend
  port:
    targetPort: 3000
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
{{- end }}
---
{{- if .Values.route.redirecthosts }}
{{- range .Values.route.redirecthosts }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "app.fullname" $ }}-{{ . | replace "." "-" }}-redirect
  annotations:
    haproxy.router.openshift.io/disable_cookies: 'true'
spec:
  host: {{ . }}
  to:
    kind: Service
    name: {{ template "app.fullname" $ }}-frontend
  port:
    targetPort: 3000
  wildcardPolicy: None
---
{{- end }}
{{- end }}