name: 1. Build & Deploy to Dev
#Will automatically run on a push to main, but can also be run manually

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write
  attestations: write
  artifact-metadata: write 

jobs:
  setup:
    runs-on: ubuntu-latest
    name: Setup Job to define outputs
    outputs:
      environment_name: dev
      helm_release_name: dev-drivebc
      image_registry: ghcr.io
      openshift_gold_url: https://dev-drivebc.apps.gold.devops.gov.bc.ca
      openshift_golddr_url: https://dev-drivebc.apps.golddr.devops.gov.bc.ca
      custom_tag: '' 
      tag_for_helm: sha-${{ github.sha }} 
    steps:
      - name: Set outputs
        run: echo "This step is required to set job outputs."

  update-openshift-gold:
    needs: [setup]
    runs-on: ubuntu-latest
    # Added the loop iteration to the name so you can distinguish them in the UI
    name: Deploy to Gold (Run ${{ matrix.iteration }}). Tag ${{ needs.setup.outputs.tag_for_helm }}
    
    strategy:
      matrix:
        iteration: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
      max-parallel: 1 # Ensures they run sequentially. Remove this line if you want all 5 to run at the same time.

    environment:
      name: ${{ needs.setup.outputs.environment_name }}
      url: ${{ needs.setup.outputs.openshift_gold_url }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v7
    - name: OC Setup
      uses: ./.github/actions/oc-setup
      with:
        server: ${{ vars.OPENSHIFT_GOLD_SERVER }}
        token: ${{ secrets.OPENSHIFT_GOLD_TOKEN }}
        namespace: ${{ vars.OPENSHIFT_NAMESPACE }}

  # GoldDR Runs after Gold Deployment due to GoldDR DB being read-only replica of Gold
  update-openshift-golddr:
    needs: [setup] 
    runs-on: ubuntu-latest
    name: Deploy to GoldDR (Run ${{ matrix.iteration }}). Tag ${{ needs.setup.outputs.tag_for_helm }}
    
    strategy:
      matrix:
        iteration: [1, 2, 3, 4, 5]
      max-parallel: 1 # Ensures they run sequentially.

    environment:
      name: ${{ needs.setup.outputs.environment_name }}
      url: ${{ needs.setup.outputs.openshift_golddr_url }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v7

    - name: OC Setup
      uses: ./.github/actions/oc-setup
      with:
        server: ${{ vars.OPENSHIFT_GOLDDR_SERVER }}
        token: ${{ secrets.OPENSHIFT_GOLDDR_TOKEN }}
        namespace: ${{ vars.OPENSHIFT_NAMESPACE }}