name: 1. Build & Deploy to Dev
#Will automatically run on a push to main, but can also be run manually

on:
  push:
    branches: [ "main" ]
    paths-ignore:
    - '.github/**'
  workflow_dispatch:


env:
  REGISTRY: ghcr.io/${{ github.repository_owner }}
  STATIC_IMAGE_NAME: drivebc-static
  DJANGO_IMAGE_NAME: drivebc-django
  REDIS_IMAGE_NAME: drivebc-redis
  OPENSHIFTJOBS_IMAGE_NAME: drivebc-openshiftjobs

jobs:
  build-static:
    runs-on: ubuntu-latest
    name: Build & Push Static Image
    environment: dev
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.STATIC_IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=raw,value=latest-dev
            type=sha,format=long
          labels:
            app=drivebc
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./compose/frontend/StaticBuild
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args:
            FONTAWESOME_PACKAGE_TOKEN=${{ secrets.FONTAWESOME_PACKAGE_TOKEN }}
            DEBUG_BUILD=true
          cache-from: type=gha
          cache-to: type=gha,mode=max
