name: 1. Build & Deploy to Dev

#Will automatically run on a push to main, but can also be run manually
on:
  push:
    branches: [ "main" ]
    paths-ignore:
    - '.github/**'
    - '.infrastructure/standbycheck/**'
    - '.infrastructure/crunchy-postgres/**'
  workflow_dispatch:

permissions:
  contents: read
  packages: write


jobs:
  setup: # Need to define variables this way because certain fields don't accept env variables (ie. environment)
    runs-on: ubuntu-latest
    name: Setup Job to define outputs
    outputs:
      environment_name: dev
      helm_release_name: dev-drivebc
      image_registry: ghcr.io
      image_repository: bcgov # In our case it's always bcgov
      openshift_gold_url: https://dev-drivebc.apps.gold.devops.gov.bc.ca
      openshift_golddr_url: https://dev-drivebc.apps.golddr.devops.gov.bc.ca
      custom_tag: '' 
      tag_for_helm: sha-${{ github.sha }} 
    steps:
      - name: Set outputs
        run: echo "This step is required to set job outputs."

  build-and-push:
    needs: [setup]
    runs-on: ubuntu-latest
    name: Build & Push ${{ matrix.name }} Image
    environment: ${{ needs.setup.outputs.environment_name }}
    outputs:
      tag: ${{ steps.meta.outputs.tags }}
    strategy:
      matrix:
        include:
          - name: Static
            image_name: drivebc-static
            dockerfile: ./compose/frontend/StaticBuild
            build_args: ''
            needs_fontawesome: true
          - name: Django
            image_name: drivebc-django
            dockerfile: ./compose/backend/Dockerfile
            build_args: |
              DEBUG_BUILD=false
            needs_fontawesome: false
          - name: Redis
            image_name: drivebc-redis
            dockerfile: ./compose/redis/Dockerfile
            build_args: ''
            needs_fontawesome: false
          - name: OpenShiftJobs
            image_name: drivebc-openshiftjobs
            dockerfile: ./compose/openshiftjobs/Dockerfile
            build_args: ''
            needs_fontawesome: false

### EVERYTHING PAST THIS POINT SHOULD BE THE SAME IN DEV, TEST AND UAT WORKFLOWS ###            

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ needs.setup.outputs.image_registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ needs.setup.outputs.image_registry }}/${{ needs.setup.outputs.image_repository }}/${{ matrix.image_name }}
          tags: |
            type=raw,value=latest
            type=raw,value=latest-${{ needs.setup.outputs.environment_name }}
            type=sha,format=long
            ${{ needs.setup.outputs.custom_tag }}
            
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
  
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: ${{ matrix.build_args }}
          secrets: |
            ${{ matrix.needs_fontawesome && format('FONTAWESOME_PACKAGE_TOKEN={0}', secrets.FONTAWESOME_PACKAGE_TOKEN) || '' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  update-openshift-gold:
    needs: [setup, build-and-push]
    runs-on: ubuntu-latest
    name: Deploy to Gold. Tag ${{ needs.setup.outputs.tag_for_helm }}
    environment:
      name: ${{ needs.setup.outputs.environment_name }}
      url: ${{ needs.setup.outputs.openshift_gold_url }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
    - name: Install CLI tools from OpenShift Mirror
      uses: redhat-actions/openshift-tools-installer@v1
      with:
        oc: "4"
        skip_cache: true
      
    - name: Authenticate and set context
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ vars.OPENSHIFT_GOLD_SERVER }}
        openshift_token: ${{ secrets.OPENSHIFT_GOLD_TOKEN }}
        namespace: ${{ vars.OPENSHIFT_NAMESPACE }}
        insecure_skip_tls_verify: false
    - name: Helm upgrade on OpenShift Gold Environment
      run: |
        helm upgrade dev-drivebc -f ./infrastructure/main/values-dev.yaml ./infrastructure/main --set static.image.tag=sha-${{ github.sha }} --set django.image.tag=sha-${{ github.sha }} --set tasks.image.tag=sha-${{ github.sha }} --set image-consumer.image.tag=sha-${{ github.sha }} --set redis.image.tag=sha-${{ github.sha }} --set openshiftjobs.image.tag=sha-${{ github.sha }}

  # GoldDR Runs after Gold Deployment due to GoldDR DB being read-only replica of Gold
  update-openshift-golddr:
    needs: [setup, update-openshift-gold] 
    runs-on: ubuntu-latest
    name: Deploy to GoldDR. Tag ${{ needs.setup.outputs.tag_for_helm }}
    environment:
      name: ${{ needs.setup.outputs.environment_name }}
      url: ${{ needs.setup.outputs.openshift_golddr_url }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Install CLI tools from OpenShift Mirror
      uses: redhat-actions/openshift-tools-installer@v1
      with:
        oc: "4"
        skip_cache: true
     
    - name: Authenticate and set context
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ vars.OPENSHIFT_GOLDDR_SERVER }}
        openshift_token: ${{ secrets.OPENSHIFT_GOLDDR_TOKEN }}
        namespace: ${{ vars.OPENSHIFT_NAMESPACE }}
        insecure_skip_tls_verify: false

    - name: Helm upgrade on OpenShift GoldDR Environment
      run: |
        helm upgrade dev-drivebc -f ./infrastructure/main/values-dev.yaml -f ./infrastructure/main/values-dev-dr.yaml ./infrastructure/main --set static.image.tag=sha-${{ github.sha }} --set django.image.tag=sha-${{ github.sha }} --set tasks.image.tag=sha-${{ github.sha }} --set image-consumer.image.tag=sha-${{ github.sha }} --set redis.image.tag=sha-${{ github.sha }} --set openshiftjobs.image.tag=sha-${{ github.sha }}



#  automatedTests:
#    needs: [versionUpdate]
#    name: Automated Smoke Test
#    uses: bcgov/DriveBC.ca-automated-tests/.github/workflows/playwright.yml@main
#    with:
#      environment: 'dev'
#    secrets: inherit
