name: 4. Promote from UAT to Prod

on: 
  workflow_dispatch: #Make sure you select a tag and not a branch if using manually
  release:
    types: [published]

env:
    IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
    REGISTRY_USER: ${{ github.actor }}
    REGISTRY_PASSWORD: ${{ github.token }}

permissions:
  packages: write

jobs:
  tag:
    runs-on: ubuntu-latest
    name: Create Tag Variable
    timeout-minutes: 1
    outputs:
      tag: ${{ steps.vars.outputs.tag }}

    steps:
      - name: Set the tag variable
        id: vars
        run: |
          vtag=${{ github.ref_name }}
          echo "tag=${{ github.ref_name }}" >> $GITHUB_OUTPUT

#This job adds 'latest-prod' docker tags to the existing image in Github Packages so it's always clear which image is current for a particular environment
  addDockerTag:
    needs: [tag]
    runs-on: ubuntu-latest
    name: Add latest-prod Tag
    steps:
    - name: Add latest-prod tag to django image
      uses: shrink/actions-docker-registry-tag@v4
      with:
        registry: ghcr.io
        repository: bcgov/drivebc-django
        target: ${{ needs.tag.outputs.tag }}
        tags: |
          latest-prod
    - name: Add latest-prod tag to static image
      uses: shrink/actions-docker-registry-tag@v4
      with:
        registry: ghcr.io
        repository: bcgov/drivebc-static
        target: ${{ needs.tag.outputs.tag }}
        tags: |
          latest-prod
    - name: Add latest-prod tag to redis image
      uses: shrink/actions-docker-registry-tag@v4
      with:
        registry: ghcr.io
        repository: bcgov/drivebc-redis
        target: ${{ needs.tag.outputs.tag }}
        tags: |
          latest-prod

    - name: Add latest-prod tag to openshiftjobs image
      uses: shrink/actions-docker-registry-tag@v4
      with:
        registry: ghcr.io
        repository: bcgov/drivebc-openshiftjobs
        target: ${{ needs.tag.outputs.tag }}
        tags: |
          latest-prod

  update-openshift-gold:
    needs: [tag]
    runs-on: ubuntu-latest
    name: Deploy Images to OpenShift Gold
    environment:
      name: prod
      url: https://beta.drivebc.ca/
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install CLI tools from OpenShift Mirror
      uses: redhat-actions/openshift-tools-installer@v1
      with:
        oc: "4"
      
    - name: Authenticate and set context
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ vars.OPENSHIFT_GOLD_SERVER }}
        openshift_token: ${{ secrets.OPENSHIFT_GOLD_TOKEN }}
        namespace: ${{ vars.OPENSHIFT_NAMESPACE }}
        insecure_skip_tls_verify: true
    - name: Helm upgrade on OpenShift Gold Environment
      run: |
        helm upgrade prod-drivebc -f ./infrastructure/main/values-prod.yaml ./infrastructure/main --set django.image.tag="${{ needs.tag.outputs.tag }}" --set redis.image.tag="${{ needs.tag.outputs.tag }}" --set static.image.tag="${{ needs.tag.outputs.tag }}" --set tasks.image.tag="${{ needs.tag.outputs.tag }}" --set openshiftjobs.image.tag="${{ needs.tag.outputs.tag }}" --set static.release="${{ github.event.release.name }}"

  # I have this run after the push to Gold because I want to make sure that Gold runs the migrations first. Gold DR can't run migrations as DB is read-only
  update-openshift-golddr:
    needs: [tag, update-openshift-gold] 
    runs-on: ubuntu-latest
    name: Deploy Images to OpenShift GoldDR
    environment:
      name: prod
      url: https://beta.drivebc.ca/
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install CLI tools from OpenShift Mirror
      uses: redhat-actions/openshift-tools-installer@v1
      with:
        oc: "4"
     
    - name: Authenticate and set context
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ vars.OPENSHIFT_GOLDDR_SERVER }}
        openshift_token: ${{ secrets.OPENSHIFT_GOLDDR_TOKEN }}
        namespace: ${{ vars.OPENSHIFT_NAMESPACE }}
        insecure_skip_tls_verify: true

    - name: Helm upgrade on OpenShift GoldDR Environment
      run: |
        helm upgrade prod-drivebc -f ./infrastructure/main/values-prod.yaml -f ./infrastructure/main/values-prod-dr.yaml ./infrastructure/main --set django.image.tag="${{ needs.tag.outputs.tag }}" --set redis.image.tag="${{ needs.tag.outputs.tag }}" --set static.image.tag="${{ needs.tag.outputs.tag }}" --set tasks.image.tag="${{ needs.tag.outputs.tag }}" --set openshiftjobs.image.tag="${{ needs.tag.outputs.tag }}" --set static.release="${{ github.event.release.name }}"
