FROM alpine:3
RUN apk update && apk upgrade
#Need goaccess 1.92 for a timezone fix. Once that version is in the regular branch, we can pull it from there.
RUN apk add goaccess --repository=https://dl-cdn.alpinelinux.org/alpine/edge/main

RUN apk add --no-cache \
    aws-cli \
    bash \
    coreutils \
    tzdata

COPY ./compose/logprocessing/entrypoint.sh /

RUN sed -i 's/\r$//g' /entrypoint.sh && chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]