# Generated by Django 4.2.3 on 2024-02-07 22:28

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regionalweather',
            old_name='location_code',
            new_name='code',
        ),
        migrations.AddField(
            model_name='regionalweather',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
