# Generated by Django 4.2.3 on 2024-01-16 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_forecast_name', models.CharField(max_length=255)),
                ('text_summary', models.TextField()),
                ('icon_code_format', models.CharField(max_length=10)),
                ('icon_code', models.CharField(max_length=10)),
                ('pop_units', models.CharField(max_length=1)),
                ('pop_value', models.IntegerField()),
                ('temperatures_text_summary', models.CharField(max_length=255)),
                ('temperature_class', models.CharField(max_length=10)),
                ('temperature_units', models.CharField(max_length=2)),
                ('temperature_value', models.IntegerField()),
                ('winds_text_summary', models.CharField(max_length=255)),
                ('precip_type_start', models.CharField(max_length=2, null=True)),
                ('precip_type_end', models.CharField(max_length=2, null=True)),
                ('precip_type_value', models.CharField(max_length=10, null=True)),
                ('wind_chill_text_summary', models.CharField(max_length=255)),
                ('relative_humidity_units', models.CharField(max_length=1)),
                ('relative_humidity_value', models.IntegerField()),
                ('uv_category', models.CharField(max_length=255, null=True)),
                ('uv_index', models.IntegerField(null=True)),
                ('uv_text_summary', models.TextField(null=True)),
                ('frost', models.TextField(null=True)),
                ('snow_level', models.TextField(null=True)),
                ('comfort', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HourlyForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_timestamp_utc', models.DateTimeField()),
                ('condition', models.CharField(max_length=255)),
                ('icon_format', models.CharField(max_length=10)),
                ('icon_code', models.CharField(max_length=10)),
                ('temperature_units', models.CharField(max_length=2)),
                ('temperature_value', models.IntegerField()),
                ('lop_value', models.IntegerField()),
                ('lop_category', models.CharField(max_length=10)),
                ('lop_units', models.CharField(max_length=1)),
                ('wind_chill_text_summary', models.TextField(null=True)),
                ('wind_chill_calculated_value', models.IntegerField(null=True)),
                ('wind_chill_units', models.CharField(max_length=2, null=True)),
                ('wind_speed_units', models.CharField(max_length=5)),
                ('wind_speed_value', models.IntegerField()),
                ('wind_direction_value', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=10)),
                ('longitude', models.CharField(max_length=10)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Precipitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
                ('period', models.CharField(max_length=20)),
                ('units', models.CharField(max_length=2)),
                ('year', models.CharField(max_length=4)),
                ('value', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RiseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunrise_utc', models.CharField(max_length=255)),
                ('sunset_utc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
                ('period', models.CharField(max_length=20)),
                ('units', models.CharField(max_length=2)),
                ('year', models.CharField(max_length=4)),
                ('value', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Wind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.IntegerField()),
                ('gust', models.IntegerField(null=True)),
                ('direction', models.CharField(max_length=10)),
                ('bearing', models.IntegerField()),
                ('index', models.CharField(max_length=10)),
                ('rank', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='weather',
            name='current_conditions',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='forecast_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='forecast_issued_utc',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='warnings_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='xml_creation_utc',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.country')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.name')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.province')),
            ],
        ),
        migrations.CreateModel(
            name='HourlyForecastGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_forecasts', models.ManyToManyField(to='weather.hourlyforecast')),
            ],
        ),
        migrations.CreateModel(
            name='ForecastGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecasts', models.ManyToManyField(to='weather.forecast')),
            ],
        ),
        migrations.CreateModel(
            name='Almanac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pop_units', models.CharField(max_length=1)),
                ('pop_value', models.DecimalField(decimal_places=1, max_digits=5)),
                ('precipitations', models.ManyToManyField(to='weather.precipitation')),
                ('temperatures', models.ManyToManyField(to='weather.temperature')),
            ],
        ),
        migrations.AddField(
            model_name='weather',
            name='almanac',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='weather.almanac'),
        ),
        migrations.AddField(
            model_name='weather',
            name='forecast_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weather.forecastgroup'),
        ),
        migrations.AddField(
            model_name='weather',
            name='hourly_forecast_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weather.hourlyforecastgroup'),
        ),
        migrations.AddField(
            model_name='weather',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weather.location'),
        ),
        migrations.AddField(
            model_name='weather',
            name='rise_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weather.riseset'),
        ),
    ]
