# Generated by Django 4.2.3 on 2024-01-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionalforecast',
            name='location_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='regionalforecast',
            name='location_latitude',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='regionalforecast',
            name='location_longitude',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='regionalforecast',
            name='location_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='regionalforecast',
            name='observation_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='regionalforecast',
            name='observation_text_summary',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='regionalforecast',
            name='observation_utc_offset',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='regionalforecast',
            name='observation_zone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='regionalforecast',
            name='region',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
