# Generated by Django 4.2.3 on 2024-02-08 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_rename_location_code_regionalweather_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regionalweather',
            old_name='location_name',
            new_name='name',
        ),
    ]
