# Generated by Django 4.2.3 on 2024-01-17 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_country_forecast_hourlyforecast_name_precipitation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('Location', models.JSONField(null=True)),
                ('Warnings', models.JSONField(null=True)),
                ('CurrentConditions', models.JSONField(null=True)),
                ('ForecastGroup', models.JSONField(null=True)),
                ('HourlyForecastGroup', models.JSONField(null=True)),
                ('RiseSet', models.JSONField(null=True)),
                ('Almanac', models.JSONField(null=True)),
                ('ForecastId', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='location',
            name='continent',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weather.country'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weather.name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weather.province'),
        ),
        migrations.AlterField(
            model_name='location',
            name='region',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='almanac',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='weather.almanac'),
        ),
    ]
