# Generated by Django 4.2.3 on 2024-01-17 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_cityforecast_alter_location_continent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalCurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('station_code', models.CharField(max_length=10)),
                ('station_latitude', models.CharField(max_length=10, null=True)),
                ('station_longitude', models.CharField(max_length=10, null=True)),
                ('station_name', models.CharField(max_length=255)),
                ('observation_name', models.CharField(max_length=50, null=True)),
                ('observation_zone', models.CharField(max_length=10, null=True)),
                ('observation_utc_offset', models.IntegerField(null=True)),
                ('observation_text_summary', models.CharField(max_length=255, null=True)),
                ('condition', models.CharField(max_length=255)),
                ('temperature_units', models.CharField(max_length=5)),
                ('temperature_value', models.FloatField()),
                ('visibility_units', models.CharField(max_length=5)),
                ('visibility_value', models.FloatField()),
                ('wind_speed_units', models.CharField(max_length=5)),
                ('wind_speed_value', models.FloatField()),
                ('wind_gust_units', models.CharField(max_length=5, null=True)),
                ('wind_gust_value', models.FloatField(null=True)),
                ('wind_direction', models.CharField(max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
