# Generated by Django 4.2.3 on 2024-02-22 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_rename_location_name_regionalweather_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('weather_station_name', models.CharField(max_length=100)),
                ('elevation', models.IntegerField(null=True)),
                ('location_description', models.TextField(null=True)),
                ('datasets', models.JSONField(default=[])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
