# Generated by Django 4.2.3 on 2024-01-17 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_regionalcurrent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionalcurrent',
            name='temperature_units',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='regionalcurrent',
            name='temperature_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='regionalcurrent',
            name='visibility_units',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='regionalcurrent',
            name='visibility_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='regionalcurrent',
            name='wind_direction',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='regionalcurrent',
            name='wind_speed_units',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='regionalcurrent',
            name='wind_speed_value',
            field=models.FloatField(null=True),
        ),
    ]
