# Generated by Django 4.2.3 on 2024-01-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_alter_regionalcurrent_temperature_units_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionalcurrent',
            name='wind_direction',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
