# Generated by Django 4.2.3 on 2024-02-29 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_squashed_0005_alter_currentweather_datasets'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentweather',
            name='location_latitude',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='currentweather',
            name='location_longitude',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
