# Generated by Django 4.2.3 on 2024-03-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_currentweather_location_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentweather',
            name='location_latitude',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='location_longitude',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
