# Generated by Django 4.2.3 on 2024-01-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_alter_regionalcurrent_wind_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='almanac',
            name='precipitations',
        ),
        migrations.RemoveField(
            model_name='almanac',
            name='temperatures',
        ),
        migrations.DeleteModel(
            name='CityForecast',
        ),
        migrations.RemoveField(
            model_name='forecastgroup',
            name='forecasts',
        ),
        migrations.RemoveField(
            model_name='hourlyforecastgroup',
            name='hourly_forecasts',
        ),
        migrations.RemoveField(
            model_name='location',
            name='country',
        ),
        migrations.RemoveField(
            model_name='location',
            name='name',
        ),
        migrations.RemoveField(
            model_name='location',
            name='province',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='almanac',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='forecast_group',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='hourly_forecast_group',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='location',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='rise_set',
        ),
        migrations.DeleteModel(
            name='Wind',
        ),
        migrations.AlterField(
            model_name='regionalcurrent',
            name='condition',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Almanac',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Forecast',
        ),
        migrations.DeleteModel(
            name='ForecastGroup',
        ),
        migrations.DeleteModel(
            name='HourlyForecast',
        ),
        migrations.DeleteModel(
            name='HourlyForecastGroup',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Name',
        ),
        migrations.DeleteModel(
            name='Precipitation',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
        migrations.DeleteModel(
            name='RiseSet',
        ),
        migrations.DeleteModel(
            name='Temperature',
        ),
        migrations.DeleteModel(
            name='Weather',
        ),
    ]
