# Generated by Django 4.2.3 on 2024-01-18 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_remove_almanac_precipitations_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regionalcurrent',
            old_name='station_name',
            new_name='region',
        ),
    ]
