# Generated by Django 4.2.3 on 2024-01-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0008_rename_station_name_regionalcurrent_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regionalcurrent',
            old_name='station_code',
            new_name='location_code',
        ),
        migrations.RenameField(
            model_name='regionalcurrent',
            old_name='station_latitude',
            new_name='location_latitude',
        ),
        migrations.RenameField(
            model_name='regionalcurrent',
            old_name='station_longitude',
            new_name='location_longitude',
        ),
        migrations.AddField(
            model_name='regionalcurrent',
            name='location_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
