# Generated by Django 4.2.3 on 2024-03-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0008_currentweather_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentweather',
            name='issuedUtc',
            field=models.DateField(null=True),
        ),
    ]
