# Generated by Django 4.2.3 on 2024-03-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0009_currentweather_issuedutc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentweather',
            name='issuedUtc',
            field=models.DateTimeField(null=True),
        ),
    ]
