# Generated by Django 4.2.3 on 2024-03-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0011_alter_currentweather_datasets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regionalweather',
            name='observation_name',
        ),
        migrations.RemoveField(
            model_name='regionalweather',
            name='observation_text_summary',
        ),
        migrations.RemoveField(
            model_name='regionalweather',
            name='observation_utc_offset',
        ),
        migrations.RemoveField(
            model_name='regionalweather',
            name='observation_zone',
        ),
        migrations.AddField(
            model_name='regionalweather',
            name='forecast_issued',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='regionalweather',
            name='observed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='regionalweather',
            name='station',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='regionalweather',
            name='sunrise',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='regionalweather',
            name='sunset',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='regionalweather',
            name='warnings',
            field=models.JSONField(null=True),
        ),
    ]
