# Generated by Django 4.2.16 on 2024-12-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0015_highelevationforecast'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentweather',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
