# Generated by Django 5.2.11 on 2026-02-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0016_currentweather_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentweather',
            name='forecast_group',
            field=models.JSONField(null=True),
        ),
    ]
