# Generated by Django 5.2.11 on 2026-02-25 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0017_currentweather_forecast_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentweather',
            name='hourly_forecast_group',
        ),
    ]
