# Generated by Django 4.2.3 on 2024-03-15 20:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('rest_stop_id', models.CharField(max_length=100, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('geometry', models.JSONField(null=True)),
                ('properties', models.JSONField(null=True)),
                ('bbox', models.JSONField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
