from apps.feed.client import FeedClient
from apps.shared.tests import BaseTest


class TestLocalWeatherFunctions(BaseTest):
    def setUp(self):
        super().setUp()
        self.client = FeedClient()

    # get_local_weather_icon_code tests
    def test_weather_icon_code(self):
        # Thunderstorm
        result = self.client.get_local_weather_icon_code("Thunderstorms", "day")
        self.assertEqual(result, '19')
        result = self.client.get_local_weather_icon_code("Chance of thunderstorms", "day")
        self.assertEqual(result, '09')
        result = self.client.get_local_weather_icon_code("Risk of thunderstorms", "day")
        self.assertEqual(result, '09')
        result = self.client.get_local_weather_icon_code("Possible thunderstorms", "day")
        self.assertEqual(result, '09')
        result = self.client.get_local_weather_icon_code("Few thunderstorms", "day")
        self.assertEqual(result, '09')
        result = self.client.get_local_weather_icon_code("Spotty thunderstorms", "day")
        self.assertEqual(result, '09')
        result = self.client.get_local_weather_icon_code("Stray thunderstorms", "day")
        self.assertEqual(result, '09')
        result = self.client.get_local_weather_icon_code("Chance of thunderstorms", "night")
        self.assertEqual(result, '39')

        # Freezing
        result = self.client.get_local_weather_icon_code("Freezing rain", "day")
        self.assertEqual(result, '14')
        result = self.client.get_local_weather_icon_code("Freezing drizzle", "day")
        self.assertEqual(result, '28')

        # Mixed precipitation
        result = self.client.get_local_weather_icon_code("Ice pellets", "day")
        self.assertEqual(result, '27')
        result = self.client.get_local_weather_icon_code("Hail", "day")
        self.assertEqual(result, '27')
        result = self.client.get_local_weather_icon_code("Rain mixed with snow", "day")
        self.assertEqual(result, '15')
        result = self.client.get_local_weather_icon_code("Wintry mix", "day")
        self.assertEqual(result, '15')
        result = self.client.get_local_weather_icon_code("Chance of rain and snow", "day")
        self.assertEqual(result, '07')
        result = self.client.get_local_weather_icon_code("Risk of mixed precipitation", "night")
        self.assertEqual(result, '37')

        # Snow
        result = self.client.get_local_weather_icon_code("Blowing snow", "day")
        self.assertEqual(result, '40')
        result = self.client.get_local_weather_icon_code("Drifting snow", "day")
        self.assertEqual(result, '40')
        result = self.client.get_local_weather_icon_code("Heavy snow", "day")
        self.assertEqual(result, '17')
        result = self.client.get_local_weather_icon_code("Snow squalls", "day")
        self.assertEqual(result, '17')
        result = self.client.get_local_weather_icon_code("Chance of flurries", "day")
        self.assertEqual(result, '08')
        result = self.client.get_local_weather_icon_code("Risk of snow", "day")
        self.assertEqual(result, '08')
        result = self.client.get_local_weather_icon_code("Possible snow", "day")
        self.assertEqual(result, '08')
        result = self.client.get_local_weather_icon_code("Few flurries", "day")
        self.assertEqual(result, '08')
        result = self.client.get_local_weather_icon_code("Spotty snow showers", "day")
        self.assertEqual(result, '08')
        result = self.client.get_local_weather_icon_code("Stray snow showers", "day")
        self.assertEqual(result, '08')
        result = self.client.get_local_weather_icon_code("Occasional snow", "day")
        self.assertEqual(result, '08')
        result = self.client.get_local_weather_icon_code("Chance of flurries", "night")
        self.assertEqual(result, '38')
        result = self.client.get_local_weather_icon_code("Light snow", "day")
        self.assertEqual(result, '16')
        result = self.client.get_local_weather_icon_code("Snow", "day")
        self.assertEqual(result, '16')

        # Rain / Drizzle
        result = self.client.get_local_weather_icon_code("Drizzle", "day")
        self.assertEqual(result, '28')
        result = self.client.get_local_weather_icon_code("Chance of rain", "day")
        self.assertEqual(result, '06')
        result = self.client.get_local_weather_icon_code("Risk of rain", "day")
        self.assertEqual(result, '06')
        result = self.client.get_local_weather_icon_code("Possible rain", "day")
        self.assertEqual(result, '06')
        result = self.client.get_local_weather_icon_code("Few rain showers", "day")
        self.assertEqual(result, '06')
        result = self.client.get_local_weather_icon_code("Spotty showers", "day")
        self.assertEqual(result, '06')
        result = self.client.get_local_weather_icon_code("Stray showers", "day")
        self.assertEqual(result, '06')
        result = self.client.get_local_weather_icon_code("Sprinkles", "day")
        self.assertEqual(result, '06')
        result = self.client.get_local_weather_icon_code("Chance of rain", "night")
        self.assertEqual(result, '36')
        result = self.client.get_local_weather_icon_code("Heavy rain", "day")
        self.assertEqual(result, '13')
        result = self.client.get_local_weather_icon_code("Showers", "day")
        self.assertEqual(result, '12')
        result = self.client.get_local_weather_icon_code("Rain", "day")
        self.assertEqual(result, '13')

        # Obscuration
        result = self.client.get_local_weather_icon_code("Smoke", "day")
        self.assertEqual(result, '44')
        result = self.client.get_local_weather_icon_code("Fog", "day")
        self.assertEqual(result, '24')
        result = self.client.get_local_weather_icon_code("Haze", "day")
        self.assertEqual(result, '23')
        result = self.client.get_local_weather_icon_code("Mist", "day")
        self.assertEqual(result, '24')

        # Sky conditions
        result = self.client.get_local_weather_icon_code("Increasing cloud", "day")
        self.assertEqual(result, '04')
        result = self.client.get_local_weather_icon_code("Clearing", "day")
        self.assertEqual(result, '05')
        result = self.client.get_local_weather_icon_code("Clearing", "night")
        self.assertEqual(result, '35')
        result = self.client.get_local_weather_icon_code("Sunny with cloud", "day")
        self.assertEqual(result, '02')
        result = self.client.get_local_weather_icon_code("Mostly sunny", "day")
        self.assertEqual(result, '01')
        result = self.client.get_local_weather_icon_code("Mostly clear", "night")
        self.assertEqual(result, '31')
        result = self.client.get_local_weather_icon_code("Clear", "night")
        self.assertEqual(result, '30')
        result = self.client.get_local_weather_icon_code("Sunny", "day")
        self.assertEqual(result, '00')
        result = self.client.get_local_weather_icon_code("Partly cloudy", "day")
        self.assertEqual(result, '22')
        result = self.client.get_local_weather_icon_code("Partly cloudy", "night")
        self.assertEqual(result, '32')
        result = self.client.get_local_weather_icon_code("Variable clouds", "day")
        self.assertEqual(result, '22')
        result = self.client.get_local_weather_icon_code("Mix of sun and cloud", "day")
        self.assertEqual(result, '02')
        result = self.client.get_local_weather_icon_code("Mostly cloudy", "day")
        self.assertEqual(result, '10')
        result = self.client.get_local_weather_icon_code("Overcast", "day")
        self.assertEqual(result, '10')
        result = self.client.get_local_weather_icon_code("Cloudy", "day")
        self.assertEqual(result, '10')

        # Wind
        result = self.client.get_local_weather_icon_code("Windy", "day")
        self.assertEqual(result, '43')
        result = self.client.get_local_weather_icon_code("Breezy", "day")
        self.assertEqual(result, '43')
        result = self.client.get_local_weather_icon_code("Gusty winds", "day")
        self.assertEqual(result, '43')

        # Dry/Cold
        result = self.client.get_local_weather_icon_code("Dry", "day")
        self.assertEqual(result, '01')
        result = self.client.get_local_weather_icon_code("Frigid", "night")
        self.assertEqual(result, '31')
        result = self.client.get_local_weather_icon_code("Cold", "night")
        self.assertEqual(result, '31')

        # Unknown/empty
        result = self.client.get_local_weather_icon_code("Unknown", "day")
        self.assertEqual(result, '')
        result = self.client.get_local_weather_icon_code("", "day")
        self.assertEqual(result, '')

    # extract_high_value tests
    def test_extract_high_value_normal(self):
        result = self.client.extract_high_value("Cloudy. Rain. High: 4.")
        self.assertEqual(result, 4.0)
        result = self.client.extract_high_value("Cloudy. Rain.")
        self.assertEqual(result, None)

    # extract_low_value tests
    def test_extract_low_value_normal(self):
        result = self.client.extract_low_value("Cloudy.  Few snow showers/flurries develop after 1-2am.  1-3 cm road snow accumulations.  Low: -2.")
        self.assertEqual(result, -2.0)
        result = self.client.extract_low_value("Cloudy.  Few snow showers/flurries develop after 1-2am.  1-3 cm road snow accumulations.")
        self.assertEqual(result, None)
